//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject.ProspectingUserAuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectingUserAuthPacket", Namespace="http://schemas.datacontract.org/2004/07/SeeffProspectingAuthService")]
    [System.SerializableAttribute()]
    public partial class ProspectingUserAuthPacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket[] BusinessUnitUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsProspectingManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket[] ManagerDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated {
            get {
                return this.AuthenticatedField;
            }
            set {
                if ((this.AuthenticatedField.Equals(value) != true)) {
                    this.AuthenticatedField = value;
                    this.RaisePropertyChanged("Authenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableCredit {
            get {
                return this.AvailableCreditField;
            }
            set {
                if ((this.AvailableCreditField.Equals(value) != true)) {
                    this.AvailableCreditField = value;
                    this.RaisePropertyChanged("AvailableCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket[] BusinessUnitUsers {
            get {
                return this.BusinessUnitUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessUnitUsersField, value) != true)) {
                    this.BusinessUnitUsersField = value;
                    this.RaisePropertyChanged("BusinessUnitUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProspectingManager {
            get {
                return this.IsProspectingManagerField;
            }
            set {
                if ((this.IsProspectingManagerField.Equals(value) != true)) {
                    this.IsProspectingManagerField = value;
                    this.RaisePropertyChanged("IsProspectingManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket[] ManagerDetails {
            get {
                return this.ManagerDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerDetailsField, value) != true)) {
                    this.ManagerDetailsField = value;
                    this.RaisePropertyChanged("ManagerDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuburbsList {
            get {
                return this.SuburbsListField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbsListField, value) != true)) {
                    this.SuburbsListField = value;
                    this.RaisePropertyChanged("SuburbsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProspectingUserAuthService.ISeeffProspectingAuthService")]
    public interface ISeeffProspectingAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/AuthenticateAndGetUserInfo", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/AuthenticateAndGetUserInfoRespons" +
            "e")]
        ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket AuthenticateAndGetUserInfo(System.Guid userGuid, System.Guid sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/AuthenticateAndGetUserInfo", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/AuthenticateAndGetUserInfoRespons" +
            "e")]
        System.Threading.Tasks.Task<ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket> AuthenticateAndGetUserInfoAsync(System.Guid userGuid, System.Guid sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/DebitUserBalance", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/DebitUserBalanceResponse")]
        decimal DebitUserBalance(decimal amount, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/DebitUserBalance", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/DebitUserBalanceResponse")]
        System.Threading.Tasks.Task<decimal> DebitUserBalanceAsync(decimal amount, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/CreditUserBalance", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/CreditUserBalanceResponse")]
        decimal CreditUserBalance(decimal amount, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/CreditUserBalance", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/CreditUserBalanceResponse")]
        System.Threading.Tasks.Task<decimal> CreditUserBalanceAsync(decimal amount, System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/RetrieveUserSignature", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/RetrieveUserSignatureResponse")]
        string RetrieveUserSignature(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/RetrieveUserSignature", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/RetrieveUserSignatureResponse")]
        System.Threading.Tasks.Task<string> RetrieveUserSignatureAsync(System.Guid userGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeeffProspectingAuthServiceChannel : ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeeffProspectingAuthServiceClient : System.ServiceModel.ClientBase<ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService>, ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService {
        
        public SeeffProspectingAuthServiceClient() {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeeffProspectingAuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket AuthenticateAndGetUserInfo(System.Guid userGuid, System.Guid sessionKey) {
            return base.Channel.AuthenticateAndGetUserInfo(userGuid, sessionKey);
        }
        
        public System.Threading.Tasks.Task<ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket> AuthenticateAndGetUserInfoAsync(System.Guid userGuid, System.Guid sessionKey) {
            return base.Channel.AuthenticateAndGetUserInfoAsync(userGuid, sessionKey);
        }
        
        public decimal DebitUserBalance(decimal amount, System.Guid userGuid) {
            return base.Channel.DebitUserBalance(amount, userGuid);
        }
        
        public System.Threading.Tasks.Task<decimal> DebitUserBalanceAsync(decimal amount, System.Guid userGuid) {
            return base.Channel.DebitUserBalanceAsync(amount, userGuid);
        }
        
        public decimal CreditUserBalance(decimal amount, System.Guid userGuid) {
            return base.Channel.CreditUserBalance(amount, userGuid);
        }
        
        public System.Threading.Tasks.Task<decimal> CreditUserBalanceAsync(decimal amount, System.Guid userGuid) {
            return base.Channel.CreditUserBalanceAsync(amount, userGuid);
        }
        
        public string RetrieveUserSignature(System.Guid userGuid) {
            return base.Channel.RetrieveUserSignature(userGuid);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUserSignatureAsync(System.Guid userGuid) {
            return base.Channel.RetrieveUserSignatureAsync(userGuid);
        }
    }
}
