//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject.ProspectingUserAuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectingUserAuthPacket", Namespace="http://schemas.datacontract.org/2004/07/SeeffProspectingAuthService")]
    [System.SerializableAttribute()]
    public partial class ProspectingUserAuthPacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableCredit {
            get {
                return this.AvailableCreditField;
            }
            set {
                if ((this.AvailableCreditField.Equals(value) != true)) {
                    this.AvailableCreditField = value;
                    this.RaisePropertyChanged("AvailableCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuburbsList {
            get {
                return this.SuburbsListField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbsListField, value) != true)) {
                    this.SuburbsListField = value;
                    this.RaisePropertyChanged("SuburbsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProspectingUserAuthService.ISeeffProspectingAuthService")]
    public interface ISeeffProspectingAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/GetUserInfo", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/GetUserInfoResponse")]
        ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket GetUserInfo(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/GetUserInfo", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket> GetUserInfoAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/TakeOneCredit", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/TakeOneCreditResponse")]
        int TakeOneCredit(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/TakeOneCredit", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/TakeOneCreditResponse")]
        System.Threading.Tasks.Task<int> TakeOneCreditAsync(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/ReimburseOneCredit", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/ReimburseOneCreditResponse")]
        int ReimburseOneCredit(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeeffProspectingAuthService/ReimburseOneCredit", ReplyAction="http://tempuri.org/ISeeffProspectingAuthService/ReimburseOneCreditResponse")]
        System.Threading.Tasks.Task<int> ReimburseOneCreditAsync(System.Guid userGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeeffProspectingAuthServiceChannel : ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeeffProspectingAuthServiceClient : System.ServiceModel.ClientBase<ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService>, ProspectingProject.ProspectingUserAuthService.ISeeffProspectingAuthService {
        
        public SeeffProspectingAuthServiceClient() {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeeffProspectingAuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeeffProspectingAuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket GetUserInfo(System.Guid userGuid) {
            return base.Channel.GetUserInfo(userGuid);
        }
        
        public System.Threading.Tasks.Task<ProspectingProject.ProspectingUserAuthService.ProspectingUserAuthPacket> GetUserInfoAsync(System.Guid userGuid) {
            return base.Channel.GetUserInfoAsync(userGuid);
        }
        
        public int TakeOneCredit(System.Guid userGuid) {
            return base.Channel.TakeOneCredit(userGuid);
        }
        
        public System.Threading.Tasks.Task<int> TakeOneCreditAsync(System.Guid userGuid) {
            return base.Channel.TakeOneCreditAsync(userGuid);
        }
        
        public int ReimburseOneCredit(System.Guid userGuid) {
            return base.Channel.ReimburseOneCredit(userGuid);
        }
        
        public System.Threading.Tasks.Task<int> ReimburseOneCreditAsync(System.Guid userGuid) {
            return base.Channel.ReimburseOneCreditAsync(userGuid);
        }
    }
}
