//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class exception_log
    {
        public int exception_log_id { get; set; }
        public string exception_string { get; set; }
        public string exception_friendly_msg { get; set; }
        public string context { get; set; }
        public System.DateTime created { get; set; }
    }
}
