//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spatial_license
    {
        public int id { get; set; }
        public Nullable<int> fk_license_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography geo_polygon { get; set; }
        public string region { get; set; }
        public string kml_coords { get; set; }
        public Nullable<int> fk_territory_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography area_center_point { get; set; }
    }
}
