//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.Service.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seeff_spatialEntities : DbContext
    {
        public seeff_spatialEntities()
            : base("name=seeff_spatialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<spatial_terretory> spatial_terretory { get; set; }
        public virtual DbSet<spatial_area> spatial_area { get; set; }
        public virtual DbSet<spatial_license> spatial_license { get; set; }
        public virtual DbSet<exception_log> exception_log { get; set; }
    }
}
