CREATE TABLE [dbo].[base_data] (
    [ls_area_id]                      INT             NULL,
    [seeff_lic_area]                  VARCHAR (100)   NULL,
    [property_id]                     INT             NULL,
    [iregdate]                        VARCHAR (8)     NULL,
    [ipurchdate]                      NUMERIC (11)    NULL,
    [title_deed_no]                   VARCHAR (20)    NULL,
    [non_gar_props_on_title]          NUMERIC (18)    NULL,
    [purch_price]                     NUMERIC (18)    NULL,
    [erf_key]                         VARCHAR (60)    NULL,
    [ea_code]                         VARCHAR (10)    NULL,
    [suburb]                          VARCHAR (40)    NULL,
    [munic_name]                      VARCHAR (40)    NULL,
    [province]                        VARCHAR (40)    NULL,
    [property_type]                   VARCHAR (3)     NULL,
    [ss_fh]                           VARCHAR (4)     NULL,
    [property_currently_in_pvt_hands] VARCHAR (10)    NULL,
    [private_registration]            VARCHAR (10)    NULL,
    [bonded_transfer]                 VARCHAR (20)    NULL,
    [suburb_id]                       INT             NULL,
    [erf_size]                        NUMERIC (18)    NULL,
    [buyer_name]                      VARCHAR (70)    NULL,
    [seller_name]                     VARCHAR (70)    NULL,
    [property_address]                VARCHAR (255)   NULL,
    [ls_resflg]                       BIT             NULL,
    [estate_name]                     VARCHAR (100)   NULL,
    [buyer_name_2]                    VARCHAR (100)   NULL,
    [multibuyer]                      VARCHAR (10)    NULL,
    [seeff_suburb]                    VARCHAR (100)   NULL,
    [seeff_suburb_id]                 INT             NULL,
    [seeff_suburb_type]               VARCHAR (10)    NULL,
    [seeff_lic_id]                    INT             NULL,
    [x]                               DECIMAL (13, 8) NULL,
    [y]                               DECIMAL (13, 8) NULL,
    [seeff_area_id]                   INT             NULL,
    [unique_id]                       NVARCHAR (50)   NULL,
    [seeff_deal]                      BIT             NULL,
    [fated]                           BIT             NULL,
    [market_share_type]               VARCHAR (1)     NULL,
    [base_data_id]                    INT             IDENTITY (1, 1) NOT NULL,
    [agency_id]                       INT             NULL,
    [street_or_unit_no]               VARCHAR (255)   NULL,
    [erf_no]                          INT             NULL,
    [portion_no]                      INT             NULL,
    [parent_property_id]              INT             NULL,
    [sale_includes_others_flag]       BIT             NULL,
    [fk_territory_id]                 INT             NULL,
    CONSTRAINT [pk_base_data_id] PRIMARY KEY CLUSTERED ([base_data_id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20141125-081308]
    ON [dbo].[base_data]([property_id] ASC);

