//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_list
    {
        public int pk_client_list_id { get; set; }
        public int fk_client_id { get; set; }
        public int fk_list_id { get; set; }
        public int fk_created_by_user_id { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual list list { get; set; }
    }
}
