//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list()
        {
            this.client_list = new HashSet<client_list>();
        }
    
        public int pk_list_id { get; set; }
        public string list_name { get; set; }
        public int fk_list_type_id { get; set; }
        public int fk_branch_id { get; set; }
        public int fk_created_by_user_id { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public bool deleted { get; set; }
    
        public virtual list_type list_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_list> client_list { get; set; }
    }
}
