//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class seeff_agents
    {
        public int agentId { get; set; }
        public string agentName { get; set; }
    }
}
