

CREATE procedure [dbo].[sp_load_new_lightstone_data_step_3]
as
begin
	-- 1266268820131001
	-- Step 8: insert into base_data the remaining records
	-- NB!!! After this, run KML Mapping step [5] Re-index all registrations
	insert into base_data ([ls_area_id]
      ,[seeff_lic_area]
      ,[property_id]
      ,[iregdate]
      ,[ipurchdate]
      ,[title_deed_no]
      ,[non_gar_props_on_title]
      ,[purch_price]
      ,[erf_key]
      ,[ea_code]
      ,[suburb]
      ,[munic_name]
      ,[province]
      ,[property_type]
      ,[ss_fh]
      ,[property_currently_in_pvt_hands]
      ,[private_registration]
      ,[bonded_transfer]
      ,[suburb_id]
      ,[erf_size]
      ,[buyer_name]
      ,[seller_name]
      ,[property_address]
      ,[street_or_unit_no]
      ,[ls_resflg]
      ,[estate_name]
      ,[buyer_name_2]
      ,[multibuyer]
      ,[seeff_suburb]
      ,[seeff_suburb_id]
      ,[seeff_suburb_type]
      ,[seeff_lic_id]
	  ,[unique_id]
	  ,[seeff_deal]
	  ,[seeff_area_id]
      ,[x]
      ,[y]
	  ,[erf_no]
	  ,[portion_no]) 
	select [ls_area_id]
      ,[seeff_lic_area]
      ,[property_id]
      ,[iregdate]
      ,[ipurchdate]
      ,[title_deed_no]
      ,[non_gar_props_on_title]
      ,[purch_price]
      ,[erf_key]
      ,[ea_code]
      ,[suburb]
      ,[munic_name]
      ,[province]
      ,[property_type]
      ,[ss_fh]
      ,[property_currently_in_pvt_hands]
      ,[private_registration]
      ,[bonded_transfer]
      ,[suburb_id]
      ,[erf_size]
      ,[buyer_name]
      ,[seller_name]
      ,[property_address]
	  ,[street_or_unit_no]
      ,[ls_resflg]
      ,[estate_name]
      ,[buyer_name_2]
      ,[multibuyer]
      ,[seeff_suburb]
      ,[seeff_suburb_id]
      ,[seeff_suburb_type]
      ,[seeff_lic_id]
	  ,[unique_id]
	  ,[seeff_deal]
	  ,[seeff_area_Id]
      ,[x]
      ,[y]
	  ,[erf_no]
	  ,[portion_no] 
	 from new_data_temp;
end;

