//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.WebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_data
    {
        public Nullable<int> ls_area_id { get; set; }
        public string seeff_lic_area { get; set; }
        public Nullable<int> property_id { get; set; }
        public string iregdate { get; set; }
        public Nullable<decimal> ipurchdate { get; set; }
        public string title_deed_no { get; set; }
        public Nullable<decimal> non_gar_props_on_title { get; set; }
        public Nullable<decimal> purch_price { get; set; }
        public string erf_key { get; set; }
        public string ea_code { get; set; }
        public string suburb { get; set; }
        public string munic_name { get; set; }
        public string province { get; set; }
        public string property_type { get; set; }
        public string ss_fh { get; set; }
        public string property_currently_in_pvt_hands { get; set; }
        public string private_registration { get; set; }
        public string bonded_transfer { get; set; }
        public Nullable<int> suburb_id { get; set; }
        public Nullable<decimal> erf_size { get; set; }
        public string buyer_name { get; set; }
        public string seller_name { get; set; }
        public string property_address { get; set; }
        public Nullable<bool> ls_resflg { get; set; }
        public string estate_name { get; set; }
        public string buyer_name_2 { get; set; }
        public string multibuyer { get; set; }
        public string seeff_suburb { get; set; }
        public Nullable<int> seeff_suburb_id { get; set; }
        public string seeff_suburb_type { get; set; }
        public Nullable<int> seeff_lic_id { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> seeff_area_id { get; set; }
        public string unique_id { get; set; }
        public Nullable<bool> seeff_deal { get; set; }
        public Nullable<bool> fated { get; set; }
        public string market_share_type { get; set; }
        public int base_data_id { get; set; }
        public Nullable<int> agency_id { get; set; }
        public string street_or_unit_no { get; set; }
        public Nullable<int> erf_no { get; set; }
        public Nullable<int> portion_no { get; set; }
        public Nullable<int> parent_property_id { get; set; }
        public Nullable<bool> sale_includes_others_flag { get; set; }
        public Nullable<int> fk_territory_id { get; set; }
        public Nullable<System.DateTime> fated_date { get; set; }
    }
}
