//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.WebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecting_property
    {
        public int prospecting_property_id { get; set; }
        public Nullable<int> licence_id { get; set; }
        public Nullable<int> seeff_area_id { get; set; }
        public Nullable<int> development_id { get; set; }
        public int lightstone_property_id { get; set; }
        public Nullable<int> propstats_id { get; set; }
        public Nullable<int> windeed_id { get; set; }
        public Nullable<int> erf_no { get; set; }
        public Nullable<int> portion_no { get; set; }
        public string property_address { get; set; }
        public string street_or_unit_no { get; set; }
        public string photo_url { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<System.DateTime> age { get; set; }
        public Nullable<int> erf_size { get; set; }
        public Nullable<int> dwell_size { get; set; }
        public string condition { get; set; }
        public Nullable<int> beds { get; set; }
        public Nullable<int> baths { get; set; }
        public Nullable<int> receptions { get; set; }
        public Nullable<int> studies { get; set; }
        public Nullable<int> garages { get; set; }
        public Nullable<int> parking_bays { get; set; }
        public Nullable<bool> pool { get; set; }
        public Nullable<bool> staff_accomodation { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string lightstone_id_or_ck_no { get; set; }
        public string lightstone_reg_date { get; set; }
        public string comments { get; set; }
        public string ss_name { get; set; }
        public string ss_number { get; set; }
        public string unit { get; set; }
        public string ss_fh { get; set; }
        public Nullable<decimal> last_purch_price { get; set; }
        public string ss_id { get; set; }
        public string ss_door_number { get; set; }
        public Nullable<bool> prospected { get; set; }
        public string farm_name { get; set; }
        public string lightstone_suburb { get; set; }
        public string ss_unique_identifier { get; set; }
        public Nullable<System.Guid> locked_by_guid { get; set; }
        public Nullable<System.DateTime> locked_datetime { get; set; }
        public string latest_reg_date { get; set; }
        public Nullable<bool> is_short_term_rental { get; set; }
        public Nullable<bool> is_long_term_rental { get; set; }
        public Nullable<bool> is_commercial { get; set; }
        public Nullable<bool> is_agricultural { get; set; }
        public Nullable<bool> is_investment { get; set; }
        public Nullable<bool> has_email { get; set; }
        public Nullable<bool> has_cell { get; set; }
        public Nullable<bool> has_landline { get; set; }
        public Nullable<bool> has_primary_email { get; set; }
        public Nullable<bool> has_primary_cell { get; set; }
        public Nullable<bool> has_primary_landline { get; set; }
    }
}
