//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeff.Spatial.WebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class seeff_areas
    {
        public int areaId { get; set; }
        public string areaName { get; set; }
        public Nullable<int> areaParentId { get; set; }
        public Nullable<int> fkAreaTypeId { get; set; }
        public Nullable<int> nDisplayOrder { get; set; }
        public string areaMap { get; set; }
        public string sideMap { get; set; }
        public string areaImageMap { get; set; }
        public string areaDescription { get; set; }
        public Nullable<int> areaPropertyCount { get; set; }
        public Nullable<int> areaResidentialPropertyBuyCount { get; set; }
        public Nullable<int> areaResidentialPropertyRentCount { get; set; }
        public Nullable<int> areaCommercialPropertyBuyCount { get; set; }
        public Nullable<int> areaCommercialPropertyRentCount { get; set; }
        public Nullable<int> areaDevelopementPropertyCount { get; set; }
        public Nullable<int> areaAgriculturalPropertyCount { get; set; }
    }
}
