#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.Linq2Sql_Classes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="seeff")]
	public partial class SeeffDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertarea(area instance);
    partial void Updatearea(area instance);
    partial void Deletearea(area instance);
    partial void Insertkml_area(kml_area instance);
    partial void Updatekml_area(kml_area instance);
    partial void Deletekml_area(kml_area instance);
    partial void InsertAreaMap(AreaMap instance);
    partial void UpdateAreaMap(AreaMap instance);
    partial void DeleteAreaMap(AreaMap instance);
    partial void Insertbranch_area(branch_area instance);
    partial void Updatebranch_area(branch_area instance);
    partial void Deletebranch_area(branch_area instance);
    partial void InsertareaType(areaType instance);
    partial void UpdateareaType(areaType instance);
    partial void DeleteareaType(areaType instance);
    partial void Insertbranch(branch instance);
    partial void Updatebranch(branch instance);
    partial void Deletebranch(branch instance);
    partial void Insertrelated_area(related_area instance);
    partial void Updaterelated_area(related_area instance);
    partial void Deleterelated_area(related_area instance);
    partial void Insertneighbouring_area(neighbouring_area instance);
    partial void Updateneighbouring_area(neighbouring_area instance);
    partial void Deleteneighbouring_area(neighbouring_area instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    #endregion
		
		public SeeffDataContext() : 
				base(global::DataManager.Properties.Settings.Default.seeffConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SeeffDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeeffDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeeffDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeeffDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<area> areas
		{
			get
			{
				return this.GetTable<area>();
			}
		}
		
		public System.Data.Linq.Table<kml_area> kml_areas
		{
			get
			{
				return this.GetTable<kml_area>();
			}
		}
		
		public System.Data.Linq.Table<AreaMap> AreaMaps
		{
			get
			{
				return this.GetTable<AreaMap>();
			}
		}
		
		public System.Data.Linq.Table<branch_area> branch_areas
		{
			get
			{
				return this.GetTable<branch_area>();
			}
		}
		
		public System.Data.Linq.Table<areaType> areaTypes
		{
			get
			{
				return this.GetTable<areaType>();
			}
		}
		
		public System.Data.Linq.Table<branch> branches
		{
			get
			{
				return this.GetTable<branch>();
			}
		}
		
		public System.Data.Linq.Table<related_area> related_areas
		{
			get
			{
				return this.GetTable<related_area>();
			}
		}
		
		public System.Data.Linq.Table<neighbouring_area> neighbouring_areas
		{
			get
			{
				return this.GetTable<neighbouring_area>();
			}
		}
		
		public System.Data.Linq.Table<search> searches
		{
			get
			{
				return this.GetTable<search>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAreaPathMap", IsComposable=true)]
		public System.Nullable<int> GetAreaPathMap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> propertyAreaId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> areaTypeId)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyAreaId, areaTypeId).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAreaParentName", IsComposable=true)]
		public string GetAreaParentName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> areaIdVar)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), areaIdVar).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.area")]
	public partial class area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _areaId;
		
		private string _areaName;
		
		private System.Nullable<int> _areaParentId;
		
		private System.Nullable<int> _fkAreaTypeId;
		
		private System.Nullable<int> _nDisplayOrder;
		
		private string _areaMap;
		
		private string _sideMap;
		
		private string _areaImageMap;
		
		private string _areaDescription;
		
		private System.Nullable<int> _areaPropertyCount;
		
		private System.Nullable<int> _areaResidentialPropertyBuyCount;
		
		private System.Nullable<int> _areaResidentialPropertyRentCount;
		
		private System.Nullable<int> _areaCommercialPropertyBuyCount;
		
		private System.Nullable<int> _areaCommercialPropertyRentCount;
		
		private System.Nullable<int> _areaDevelopementPropertyCount;
		
		private System.Nullable<int> _areaAgriculturalPropertyCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareaIdChanging(int value);
    partial void OnareaIdChanged();
    partial void OnareaNameChanging(string value);
    partial void OnareaNameChanged();
    partial void OnareaParentIdChanging(System.Nullable<int> value);
    partial void OnareaParentIdChanged();
    partial void OnfkAreaTypeIdChanging(System.Nullable<int> value);
    partial void OnfkAreaTypeIdChanged();
    partial void OnnDisplayOrderChanging(System.Nullable<int> value);
    partial void OnnDisplayOrderChanged();
    partial void OnareaMapChanging(string value);
    partial void OnareaMapChanged();
    partial void OnsideMapChanging(string value);
    partial void OnsideMapChanged();
    partial void OnareaImageMapChanging(string value);
    partial void OnareaImageMapChanged();
    partial void OnareaDescriptionChanging(string value);
    partial void OnareaDescriptionChanged();
    partial void OnareaPropertyCountChanging(System.Nullable<int> value);
    partial void OnareaPropertyCountChanged();
    partial void OnareaResidentialPropertyBuyCountChanging(System.Nullable<int> value);
    partial void OnareaResidentialPropertyBuyCountChanged();
    partial void OnareaResidentialPropertyRentCountChanging(System.Nullable<int> value);
    partial void OnareaResidentialPropertyRentCountChanged();
    partial void OnareaCommercialPropertyBuyCountChanging(System.Nullable<int> value);
    partial void OnareaCommercialPropertyBuyCountChanged();
    partial void OnareaCommercialPropertyRentCountChanging(System.Nullable<int> value);
    partial void OnareaCommercialPropertyRentCountChanged();
    partial void OnareaDevelopementPropertyCountChanging(System.Nullable<int> value);
    partial void OnareaDevelopementPropertyCountChanged();
    partial void OnareaAgriculturalPropertyCountChanging(System.Nullable<int> value);
    partial void OnareaAgriculturalPropertyCountChanged();
    #endregion
		
		public area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int areaId
		{
			get
			{
				return this._areaId;
			}
			set
			{
				if ((this._areaId != value))
				{
					this.OnareaIdChanging(value);
					this.SendPropertyChanging();
					this._areaId = value;
					this.SendPropertyChanged("areaId");
					this.OnareaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaName", DbType="NVarChar(100)")]
		public string areaName
		{
			get
			{
				return this._areaName;
			}
			set
			{
				if ((this._areaName != value))
				{
					this.OnareaNameChanging(value);
					this.SendPropertyChanging();
					this._areaName = value;
					this.SendPropertyChanged("areaName");
					this.OnareaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaParentId", DbType="Int")]
		public System.Nullable<int> areaParentId
		{
			get
			{
				return this._areaParentId;
			}
			set
			{
				if ((this._areaParentId != value))
				{
					this.OnareaParentIdChanging(value);
					this.SendPropertyChanging();
					this._areaParentId = value;
					this.SendPropertyChanged("areaParentId");
					this.OnareaParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaTypeId", DbType="Int")]
		public System.Nullable<int> fkAreaTypeId
		{
			get
			{
				return this._fkAreaTypeId;
			}
			set
			{
				if ((this._fkAreaTypeId != value))
				{
					this.OnfkAreaTypeIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaTypeId = value;
					this.SendPropertyChanged("fkAreaTypeId");
					this.OnfkAreaTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nDisplayOrder", DbType="Int")]
		public System.Nullable<int> nDisplayOrder
		{
			get
			{
				return this._nDisplayOrder;
			}
			set
			{
				if ((this._nDisplayOrder != value))
				{
					this.OnnDisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._nDisplayOrder = value;
					this.SendPropertyChanged("nDisplayOrder");
					this.OnnDisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaMap", DbType="NVarChar(50)")]
		public string areaMap
		{
			get
			{
				return this._areaMap;
			}
			set
			{
				if ((this._areaMap != value))
				{
					this.OnareaMapChanging(value);
					this.SendPropertyChanging();
					this._areaMap = value;
					this.SendPropertyChanged("areaMap");
					this.OnareaMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sideMap", DbType="NVarChar(50)")]
		public string sideMap
		{
			get
			{
				return this._sideMap;
			}
			set
			{
				if ((this._sideMap != value))
				{
					this.OnsideMapChanging(value);
					this.SendPropertyChanging();
					this._sideMap = value;
					this.SendPropertyChanged("sideMap");
					this.OnsideMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaImageMap", DbType="NVarChar(4000)")]
		public string areaImageMap
		{
			get
			{
				return this._areaImageMap;
			}
			set
			{
				if ((this._areaImageMap != value))
				{
					this.OnareaImageMapChanging(value);
					this.SendPropertyChanging();
					this._areaImageMap = value;
					this.SendPropertyChanged("areaImageMap");
					this.OnareaImageMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaDescription", DbType="NVarChar(4000)")]
		public string areaDescription
		{
			get
			{
				return this._areaDescription;
			}
			set
			{
				if ((this._areaDescription != value))
				{
					this.OnareaDescriptionChanging(value);
					this.SendPropertyChanging();
					this._areaDescription = value;
					this.SendPropertyChanged("areaDescription");
					this.OnareaDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaPropertyCount", DbType="Int")]
		public System.Nullable<int> areaPropertyCount
		{
			get
			{
				return this._areaPropertyCount;
			}
			set
			{
				if ((this._areaPropertyCount != value))
				{
					this.OnareaPropertyCountChanging(value);
					this.SendPropertyChanging();
					this._areaPropertyCount = value;
					this.SendPropertyChanged("areaPropertyCount");
					this.OnareaPropertyCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaResidentialPropertyBuyCount", DbType="Int")]
		public System.Nullable<int> areaResidentialPropertyBuyCount
		{
			get
			{
				return this._areaResidentialPropertyBuyCount;
			}
			set
			{
				if ((this._areaResidentialPropertyBuyCount != value))
				{
					this.OnareaResidentialPropertyBuyCountChanging(value);
					this.SendPropertyChanging();
					this._areaResidentialPropertyBuyCount = value;
					this.SendPropertyChanged("areaResidentialPropertyBuyCount");
					this.OnareaResidentialPropertyBuyCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaResidentialPropertyRentCount", DbType="Int")]
		public System.Nullable<int> areaResidentialPropertyRentCount
		{
			get
			{
				return this._areaResidentialPropertyRentCount;
			}
			set
			{
				if ((this._areaResidentialPropertyRentCount != value))
				{
					this.OnareaResidentialPropertyRentCountChanging(value);
					this.SendPropertyChanging();
					this._areaResidentialPropertyRentCount = value;
					this.SendPropertyChanged("areaResidentialPropertyRentCount");
					this.OnareaResidentialPropertyRentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCommercialPropertyBuyCount", DbType="Int")]
		public System.Nullable<int> areaCommercialPropertyBuyCount
		{
			get
			{
				return this._areaCommercialPropertyBuyCount;
			}
			set
			{
				if ((this._areaCommercialPropertyBuyCount != value))
				{
					this.OnareaCommercialPropertyBuyCountChanging(value);
					this.SendPropertyChanging();
					this._areaCommercialPropertyBuyCount = value;
					this.SendPropertyChanged("areaCommercialPropertyBuyCount");
					this.OnareaCommercialPropertyBuyCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCommercialPropertyRentCount", DbType="Int")]
		public System.Nullable<int> areaCommercialPropertyRentCount
		{
			get
			{
				return this._areaCommercialPropertyRentCount;
			}
			set
			{
				if ((this._areaCommercialPropertyRentCount != value))
				{
					this.OnareaCommercialPropertyRentCountChanging(value);
					this.SendPropertyChanging();
					this._areaCommercialPropertyRentCount = value;
					this.SendPropertyChanged("areaCommercialPropertyRentCount");
					this.OnareaCommercialPropertyRentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaDevelopementPropertyCount", DbType="Int")]
		public System.Nullable<int> areaDevelopementPropertyCount
		{
			get
			{
				return this._areaDevelopementPropertyCount;
			}
			set
			{
				if ((this._areaDevelopementPropertyCount != value))
				{
					this.OnareaDevelopementPropertyCountChanging(value);
					this.SendPropertyChanging();
					this._areaDevelopementPropertyCount = value;
					this.SendPropertyChanged("areaDevelopementPropertyCount");
					this.OnareaDevelopementPropertyCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaAgriculturalPropertyCount", DbType="Int")]
		public System.Nullable<int> areaAgriculturalPropertyCount
		{
			get
			{
				return this._areaAgriculturalPropertyCount;
			}
			set
			{
				if ((this._areaAgriculturalPropertyCount != value))
				{
					this.OnareaAgriculturalPropertyCountChanging(value);
					this.SendPropertyChanging();
					this._areaAgriculturalPropertyCount = value;
					this.SendPropertyChanged("areaAgriculturalPropertyCount");
					this.OnareaAgriculturalPropertyCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kml_area")]
	public partial class kml_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _area_id;
		
		private decimal _latitude;
		
		private decimal _longitude;
		
		private char _area_type;
		
		private int _seq;
		
		private int _kml_area_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onarea_idChanging(int value);
    partial void Onarea_idChanged();
    partial void OnlatitudeChanging(decimal value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(decimal value);
    partial void OnlongitudeChanged();
    partial void Onarea_typeChanging(char value);
    partial void Onarea_typeChanged();
    partial void OnseqChanging(int value);
    partial void OnseqChanged();
    partial void Onkml_area_idChanging(int value);
    partial void Onkml_area_idChanged();
    #endregion
		
		public kml_area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_id", DbType="Int NOT NULL")]
		public int area_id
		{
			get
			{
				return this._area_id;
			}
			set
			{
				if ((this._area_id != value))
				{
					this.Onarea_idChanging(value);
					this.SendPropertyChanging();
					this._area_id = value;
					this.SendPropertyChanged("area_id");
					this.Onarea_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_type", DbType="Char(1) NOT NULL")]
		public char area_type
		{
			get
			{
				return this._area_type;
			}
			set
			{
				if ((this._area_type != value))
				{
					this.Onarea_typeChanging(value);
					this.SendPropertyChanging();
					this._area_type = value;
					this.SendPropertyChanged("area_type");
					this.Onarea_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", DbType="Int NOT NULL")]
		public int seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this.OnseqChanging(value);
					this.SendPropertyChanging();
					this._seq = value;
					this.SendPropertyChanged("seq");
					this.OnseqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kml_area_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kml_area_id
		{
			get
			{
				return this._kml_area_id;
			}
			set
			{
				if ((this._kml_area_id != value))
				{
					this.Onkml_area_idChanging(value);
					this.SendPropertyChanging();
					this._kml_area_id = value;
					this.SendPropertyChanged("kml_area_id");
					this.Onkml_area_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AreaMap")]
	public partial class AreaMap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _areaMapId;
		
		private string _sPath;
		
		private System.Nullable<int> _fkAreaId;
		
		private System.Nullable<int> _fkAreaParentId;
		
		private string _areaName;
		
		private System.Nullable<int> _fkAreaTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareaMapIdChanging(long value);
    partial void OnareaMapIdChanged();
    partial void OnsPathChanging(string value);
    partial void OnsPathChanged();
    partial void OnfkAreaIdChanging(System.Nullable<int> value);
    partial void OnfkAreaIdChanged();
    partial void OnfkAreaParentIdChanging(System.Nullable<int> value);
    partial void OnfkAreaParentIdChanged();
    partial void OnareaNameChanging(string value);
    partial void OnareaNameChanged();
    partial void OnfkAreaTypeIdChanging(System.Nullable<int> value);
    partial void OnfkAreaTypeIdChanged();
    #endregion
		
		public AreaMap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaMapId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long areaMapId
		{
			get
			{
				return this._areaMapId;
			}
			set
			{
				if ((this._areaMapId != value))
				{
					this.OnareaMapIdChanging(value);
					this.SendPropertyChanging();
					this._areaMapId = value;
					this.SendPropertyChanged("areaMapId");
					this.OnareaMapIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPath", DbType="NVarChar(2000)")]
		public string sPath
		{
			get
			{
				return this._sPath;
			}
			set
			{
				if ((this._sPath != value))
				{
					this.OnsPathChanging(value);
					this.SendPropertyChanging();
					this._sPath = value;
					this.SendPropertyChanged("sPath");
					this.OnsPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int")]
		public System.Nullable<int> fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this.OnfkAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaId = value;
					this.SendPropertyChanged("fkAreaId");
					this.OnfkAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaParentId", DbType="Int")]
		public System.Nullable<int> fkAreaParentId
		{
			get
			{
				return this._fkAreaParentId;
			}
			set
			{
				if ((this._fkAreaParentId != value))
				{
					this.OnfkAreaParentIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaParentId = value;
					this.SendPropertyChanged("fkAreaParentId");
					this.OnfkAreaParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaName", DbType="VarChar(100)")]
		public string areaName
		{
			get
			{
				return this._areaName;
			}
			set
			{
				if ((this._areaName != value))
				{
					this.OnareaNameChanging(value);
					this.SendPropertyChanging();
					this._areaName = value;
					this.SendPropertyChanged("areaName");
					this.OnareaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaTypeId", DbType="Int")]
		public System.Nullable<int> fkAreaTypeId
		{
			get
			{
				return this._fkAreaTypeId;
			}
			set
			{
				if ((this._fkAreaTypeId != value))
				{
					this.OnfkAreaTypeIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaTypeId = value;
					this.SendPropertyChanged("fkAreaTypeId");
					this.OnfkAreaTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.branch_area")]
	public partial class branch_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _branch_areaId;
		
		private System.Nullable<int> _fkAreaId;
		
		private System.Nullable<int> _fkBranchId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbranch_areaIdChanging(int value);
    partial void Onbranch_areaIdChanged();
    partial void OnfkAreaIdChanging(System.Nullable<int> value);
    partial void OnfkAreaIdChanged();
    partial void OnfkBranchIdChanging(System.Nullable<int> value);
    partial void OnfkBranchIdChanged();
    #endregion
		
		public branch_area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_areaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int branch_areaId
		{
			get
			{
				return this._branch_areaId;
			}
			set
			{
				if ((this._branch_areaId != value))
				{
					this.Onbranch_areaIdChanging(value);
					this.SendPropertyChanging();
					this._branch_areaId = value;
					this.SendPropertyChanged("branch_areaId");
					this.Onbranch_areaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int")]
		public System.Nullable<int> fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this.OnfkAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaId = value;
					this.SendPropertyChanged("fkAreaId");
					this.OnfkAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkBranchId", DbType="Int")]
		public System.Nullable<int> fkBranchId
		{
			get
			{
				return this._fkBranchId;
			}
			set
			{
				if ((this._fkBranchId != value))
				{
					this.OnfkBranchIdChanging(value);
					this.SendPropertyChanging();
					this._fkBranchId = value;
					this.SendPropertyChanged("fkBranchId");
					this.OnfkBranchIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.areaType")]
	public partial class areaType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _areaTypeId;
		
		private string _areaTypeName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareaTypeIdChanging(int value);
    partial void OnareaTypeIdChanged();
    partial void OnareaTypeNameChanging(string value);
    partial void OnareaTypeNameChanged();
    #endregion
		
		public areaType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int areaTypeId
		{
			get
			{
				return this._areaTypeId;
			}
			set
			{
				if ((this._areaTypeId != value))
				{
					this.OnareaTypeIdChanging(value);
					this.SendPropertyChanging();
					this._areaTypeId = value;
					this.SendPropertyChanged("areaTypeId");
					this.OnareaTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaTypeName", DbType="NVarChar(50)")]
		public string areaTypeName
		{
			get
			{
				return this._areaTypeName;
			}
			set
			{
				if ((this._areaTypeName != value))
				{
					this.OnareaTypeNameChanging(value);
					this.SendPropertyChanging();
					this._areaTypeName = value;
					this.SendPropertyChanged("areaTypeName");
					this.OnareaTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.branch")]
	public partial class branch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _branchId;
		
		private string _branchName;
		
		private string _branchURL;
		
		private string _branchDialCode;
		
		private string _branchTelephone;
		
		private string _branchFax;
		
		private string _branchCell;
		
		private string _branchPostalAddress;
		
		private string _branchPhysicalAddress;
		
		private string _branchEmail;
		
		private System.Nullable<int> _branchContact;
		
		private string _branchVax;
		
		private System.Nullable<int> _fkBranchTypeId;
		
		private System.Nullable<int> _fkAreaId;
		
		private System.Nullable<byte> _fkCountryId;
		
		private System.Nullable<bool> _branchActive;
		
		private int _branchParentId;
		
		private string _branchCopy;
		
		private string _branchSpeciality;
		
		private string _branchOpeningHours;
		
		private string _branchLicenseeInformation;
		
		private System.Nullable<byte> _branchSubscribedPropertyGenie;
		
		private System.Nullable<int> _propCtrlId;
		
		private string _virtualTour_width;
		
		private string _virtualTour_height;
		
		private int _branchViewOnly;
		
		private System.Nullable<int> _updatedByUserId;
		
		private System.Nullable<System.DateTime> _lastUpdated;
		
		private string _branchLatitude;
		
		private string _branchLongitude;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbranchIdChanging(int value);
    partial void OnbranchIdChanged();
    partial void OnbranchNameChanging(string value);
    partial void OnbranchNameChanged();
    partial void OnbranchURLChanging(string value);
    partial void OnbranchURLChanged();
    partial void OnbranchDialCodeChanging(string value);
    partial void OnbranchDialCodeChanged();
    partial void OnbranchTelephoneChanging(string value);
    partial void OnbranchTelephoneChanged();
    partial void OnbranchFaxChanging(string value);
    partial void OnbranchFaxChanged();
    partial void OnbranchCellChanging(string value);
    partial void OnbranchCellChanged();
    partial void OnbranchPostalAddressChanging(string value);
    partial void OnbranchPostalAddressChanged();
    partial void OnbranchPhysicalAddressChanging(string value);
    partial void OnbranchPhysicalAddressChanged();
    partial void OnbranchEmailChanging(string value);
    partial void OnbranchEmailChanged();
    partial void OnbranchContactChanging(System.Nullable<int> value);
    partial void OnbranchContactChanged();
    partial void OnbranchVaxChanging(string value);
    partial void OnbranchVaxChanged();
    partial void OnfkBranchTypeIdChanging(System.Nullable<int> value);
    partial void OnfkBranchTypeIdChanged();
    partial void OnfkAreaIdChanging(System.Nullable<int> value);
    partial void OnfkAreaIdChanged();
    partial void OnfkCountryIdChanging(System.Nullable<byte> value);
    partial void OnfkCountryIdChanged();
    partial void OnbranchActiveChanging(System.Nullable<bool> value);
    partial void OnbranchActiveChanged();
    partial void OnbranchParentIdChanging(int value);
    partial void OnbranchParentIdChanged();
    partial void OnbranchCopyChanging(string value);
    partial void OnbranchCopyChanged();
    partial void OnbranchSpecialityChanging(string value);
    partial void OnbranchSpecialityChanged();
    partial void OnbranchOpeningHoursChanging(string value);
    partial void OnbranchOpeningHoursChanged();
    partial void OnbranchLicenseeInformationChanging(string value);
    partial void OnbranchLicenseeInformationChanged();
    partial void OnbranchSubscribedPropertyGenieChanging(System.Nullable<byte> value);
    partial void OnbranchSubscribedPropertyGenieChanged();
    partial void OnpropCtrlIdChanging(System.Nullable<int> value);
    partial void OnpropCtrlIdChanged();
    partial void OnvirtualTour_widthChanging(string value);
    partial void OnvirtualTour_widthChanged();
    partial void OnvirtualTour_heightChanging(string value);
    partial void OnvirtualTour_heightChanged();
    partial void OnbranchViewOnlyChanging(int value);
    partial void OnbranchViewOnlyChanged();
    partial void OnupdatedByUserIdChanging(System.Nullable<int> value);
    partial void OnupdatedByUserIdChanged();
    partial void OnlastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastUpdatedChanged();
    partial void OnbranchLatitudeChanging(string value);
    partial void OnbranchLatitudeChanged();
    partial void OnbranchLongitudeChanging(string value);
    partial void OnbranchLongitudeChanged();
    #endregion
		
		public branch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int branchId
		{
			get
			{
				return this._branchId;
			}
			set
			{
				if ((this._branchId != value))
				{
					this.OnbranchIdChanging(value);
					this.SendPropertyChanging();
					this._branchId = value;
					this.SendPropertyChanged("branchId");
					this.OnbranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchName", DbType="NVarChar(100)")]
		public string branchName
		{
			get
			{
				return this._branchName;
			}
			set
			{
				if ((this._branchName != value))
				{
					this.OnbranchNameChanging(value);
					this.SendPropertyChanging();
					this._branchName = value;
					this.SendPropertyChanged("branchName");
					this.OnbranchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchURL", DbType="NVarChar(255)")]
		public string branchURL
		{
			get
			{
				return this._branchURL;
			}
			set
			{
				if ((this._branchURL != value))
				{
					this.OnbranchURLChanging(value);
					this.SendPropertyChanging();
					this._branchURL = value;
					this.SendPropertyChanged("branchURL");
					this.OnbranchURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchDialCode", DbType="Char(50)")]
		public string branchDialCode
		{
			get
			{
				return this._branchDialCode;
			}
			set
			{
				if ((this._branchDialCode != value))
				{
					this.OnbranchDialCodeChanging(value);
					this.SendPropertyChanging();
					this._branchDialCode = value;
					this.SendPropertyChanged("branchDialCode");
					this.OnbranchDialCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchTelephone", DbType="Char(50)")]
		public string branchTelephone
		{
			get
			{
				return this._branchTelephone;
			}
			set
			{
				if ((this._branchTelephone != value))
				{
					this.OnbranchTelephoneChanging(value);
					this.SendPropertyChanging();
					this._branchTelephone = value;
					this.SendPropertyChanged("branchTelephone");
					this.OnbranchTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchFax", DbType="Char(50)")]
		public string branchFax
		{
			get
			{
				return this._branchFax;
			}
			set
			{
				if ((this._branchFax != value))
				{
					this.OnbranchFaxChanging(value);
					this.SendPropertyChanging();
					this._branchFax = value;
					this.SendPropertyChanged("branchFax");
					this.OnbranchFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchCell", DbType="Char(50)")]
		public string branchCell
		{
			get
			{
				return this._branchCell;
			}
			set
			{
				if ((this._branchCell != value))
				{
					this.OnbranchCellChanging(value);
					this.SendPropertyChanging();
					this._branchCell = value;
					this.SendPropertyChanged("branchCell");
					this.OnbranchCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchPostalAddress", DbType="NVarChar(500)")]
		public string branchPostalAddress
		{
			get
			{
				return this._branchPostalAddress;
			}
			set
			{
				if ((this._branchPostalAddress != value))
				{
					this.OnbranchPostalAddressChanging(value);
					this.SendPropertyChanging();
					this._branchPostalAddress = value;
					this.SendPropertyChanged("branchPostalAddress");
					this.OnbranchPostalAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchPhysicalAddress", DbType="NVarChar(500)")]
		public string branchPhysicalAddress
		{
			get
			{
				return this._branchPhysicalAddress;
			}
			set
			{
				if ((this._branchPhysicalAddress != value))
				{
					this.OnbranchPhysicalAddressChanging(value);
					this.SendPropertyChanging();
					this._branchPhysicalAddress = value;
					this.SendPropertyChanged("branchPhysicalAddress");
					this.OnbranchPhysicalAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchEmail", DbType="NVarChar(150)")]
		public string branchEmail
		{
			get
			{
				return this._branchEmail;
			}
			set
			{
				if ((this._branchEmail != value))
				{
					this.OnbranchEmailChanging(value);
					this.SendPropertyChanging();
					this._branchEmail = value;
					this.SendPropertyChanged("branchEmail");
					this.OnbranchEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchContact", DbType="Int")]
		public System.Nullable<int> branchContact
		{
			get
			{
				return this._branchContact;
			}
			set
			{
				if ((this._branchContact != value))
				{
					this.OnbranchContactChanging(value);
					this.SendPropertyChanging();
					this._branchContact = value;
					this.SendPropertyChanged("branchContact");
					this.OnbranchContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchVax", DbType="VarChar(20)")]
		public string branchVax
		{
			get
			{
				return this._branchVax;
			}
			set
			{
				if ((this._branchVax != value))
				{
					this.OnbranchVaxChanging(value);
					this.SendPropertyChanging();
					this._branchVax = value;
					this.SendPropertyChanged("branchVax");
					this.OnbranchVaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkBranchTypeId", DbType="Int")]
		public System.Nullable<int> fkBranchTypeId
		{
			get
			{
				return this._fkBranchTypeId;
			}
			set
			{
				if ((this._fkBranchTypeId != value))
				{
					this.OnfkBranchTypeIdChanging(value);
					this.SendPropertyChanging();
					this._fkBranchTypeId = value;
					this.SendPropertyChanged("fkBranchTypeId");
					this.OnfkBranchTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int")]
		public System.Nullable<int> fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this.OnfkAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaId = value;
					this.SendPropertyChanged("fkAreaId");
					this.OnfkAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCountryId", DbType="TinyInt")]
		public System.Nullable<byte> fkCountryId
		{
			get
			{
				return this._fkCountryId;
			}
			set
			{
				if ((this._fkCountryId != value))
				{
					this.OnfkCountryIdChanging(value);
					this.SendPropertyChanging();
					this._fkCountryId = value;
					this.SendPropertyChanged("fkCountryId");
					this.OnfkCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchActive", DbType="Bit")]
		public System.Nullable<bool> branchActive
		{
			get
			{
				return this._branchActive;
			}
			set
			{
				if ((this._branchActive != value))
				{
					this.OnbranchActiveChanging(value);
					this.SendPropertyChanging();
					this._branchActive = value;
					this.SendPropertyChanged("branchActive");
					this.OnbranchActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchParentId", DbType="Int NOT NULL")]
		public int branchParentId
		{
			get
			{
				return this._branchParentId;
			}
			set
			{
				if ((this._branchParentId != value))
				{
					this.OnbranchParentIdChanging(value);
					this.SendPropertyChanging();
					this._branchParentId = value;
					this.SendPropertyChanged("branchParentId");
					this.OnbranchParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchCopy", DbType="NVarChar(4000)")]
		public string branchCopy
		{
			get
			{
				return this._branchCopy;
			}
			set
			{
				if ((this._branchCopy != value))
				{
					this.OnbranchCopyChanging(value);
					this.SendPropertyChanging();
					this._branchCopy = value;
					this.SendPropertyChanged("branchCopy");
					this.OnbranchCopyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchSpeciality", DbType="NVarChar(4000)")]
		public string branchSpeciality
		{
			get
			{
				return this._branchSpeciality;
			}
			set
			{
				if ((this._branchSpeciality != value))
				{
					this.OnbranchSpecialityChanging(value);
					this.SendPropertyChanging();
					this._branchSpeciality = value;
					this.SendPropertyChanged("branchSpeciality");
					this.OnbranchSpecialityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchOpeningHours", DbType="VarChar(200)")]
		public string branchOpeningHours
		{
			get
			{
				return this._branchOpeningHours;
			}
			set
			{
				if ((this._branchOpeningHours != value))
				{
					this.OnbranchOpeningHoursChanging(value);
					this.SendPropertyChanging();
					this._branchOpeningHours = value;
					this.SendPropertyChanged("branchOpeningHours");
					this.OnbranchOpeningHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchLicenseeInformation", DbType="NVarChar(4000)")]
		public string branchLicenseeInformation
		{
			get
			{
				return this._branchLicenseeInformation;
			}
			set
			{
				if ((this._branchLicenseeInformation != value))
				{
					this.OnbranchLicenseeInformationChanging(value);
					this.SendPropertyChanging();
					this._branchLicenseeInformation = value;
					this.SendPropertyChanged("branchLicenseeInformation");
					this.OnbranchLicenseeInformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchSubscribedPropertyGenie", DbType="TinyInt")]
		public System.Nullable<byte> branchSubscribedPropertyGenie
		{
			get
			{
				return this._branchSubscribedPropertyGenie;
			}
			set
			{
				if ((this._branchSubscribedPropertyGenie != value))
				{
					this.OnbranchSubscribedPropertyGenieChanging(value);
					this.SendPropertyChanging();
					this._branchSubscribedPropertyGenie = value;
					this.SendPropertyChanged("branchSubscribedPropertyGenie");
					this.OnbranchSubscribedPropertyGenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propCtrlId", DbType="Int")]
		public System.Nullable<int> propCtrlId
		{
			get
			{
				return this._propCtrlId;
			}
			set
			{
				if ((this._propCtrlId != value))
				{
					this.OnpropCtrlIdChanging(value);
					this.SendPropertyChanging();
					this._propCtrlId = value;
					this.SendPropertyChanged("propCtrlId");
					this.OnpropCtrlIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_virtualTour_width", DbType="VarChar(100)")]
		public string virtualTour_width
		{
			get
			{
				return this._virtualTour_width;
			}
			set
			{
				if ((this._virtualTour_width != value))
				{
					this.OnvirtualTour_widthChanging(value);
					this.SendPropertyChanging();
					this._virtualTour_width = value;
					this.SendPropertyChanged("virtualTour_width");
					this.OnvirtualTour_widthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_virtualTour_height", DbType="VarChar(100)")]
		public string virtualTour_height
		{
			get
			{
				return this._virtualTour_height;
			}
			set
			{
				if ((this._virtualTour_height != value))
				{
					this.OnvirtualTour_heightChanging(value);
					this.SendPropertyChanging();
					this._virtualTour_height = value;
					this.SendPropertyChanged("virtualTour_height");
					this.OnvirtualTour_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchViewOnly", DbType="Int NOT NULL")]
		public int branchViewOnly
		{
			get
			{
				return this._branchViewOnly;
			}
			set
			{
				if ((this._branchViewOnly != value))
				{
					this.OnbranchViewOnlyChanging(value);
					this.SendPropertyChanging();
					this._branchViewOnly = value;
					this.SendPropertyChanged("branchViewOnly");
					this.OnbranchViewOnlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedByUserId", DbType="Int")]
		public System.Nullable<int> updatedByUserId
		{
			get
			{
				return this._updatedByUserId;
			}
			set
			{
				if ((this._updatedByUserId != value))
				{
					this.OnupdatedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._updatedByUserId = value;
					this.SendPropertyChanged("updatedByUserId");
					this.OnupdatedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastUpdated
		{
			get
			{
				return this._lastUpdated;
			}
			set
			{
				if ((this._lastUpdated != value))
				{
					this.OnlastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._lastUpdated = value;
					this.SendPropertyChanged("lastUpdated");
					this.OnlastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchLatitude", DbType="VarChar(255)")]
		public string branchLatitude
		{
			get
			{
				return this._branchLatitude;
			}
			set
			{
				if ((this._branchLatitude != value))
				{
					this.OnbranchLatitudeChanging(value);
					this.SendPropertyChanging();
					this._branchLatitude = value;
					this.SendPropertyChanged("branchLatitude");
					this.OnbranchLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchLongitude", DbType="VarChar(255)")]
		public string branchLongitude
		{
			get
			{
				return this._branchLongitude;
			}
			set
			{
				if ((this._branchLongitude != value))
				{
					this.OnbranchLongitudeChanging(value);
					this.SendPropertyChanging();
					this._branchLongitude = value;
					this.SendPropertyChanged("branchLongitude");
					this.OnbranchLongitudeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.related_area")]
	public partial class related_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _related_areaId;
		
		private int _fkAreaId;
		
		private int _fkRelatedAreaId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrelated_areaIdChanging(int value);
    partial void Onrelated_areaIdChanged();
    partial void OnfkAreaIdChanging(int value);
    partial void OnfkAreaIdChanged();
    partial void OnfkRelatedAreaIdChanging(int value);
    partial void OnfkRelatedAreaIdChanged();
    #endregion
		
		public related_area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_related_areaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int related_areaId
		{
			get
			{
				return this._related_areaId;
			}
			set
			{
				if ((this._related_areaId != value))
				{
					this.Onrelated_areaIdChanging(value);
					this.SendPropertyChanging();
					this._related_areaId = value;
					this.SendPropertyChanged("related_areaId");
					this.Onrelated_areaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int NOT NULL")]
		public int fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this.OnfkAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaId = value;
					this.SendPropertyChanged("fkAreaId");
					this.OnfkAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkRelatedAreaId", DbType="Int NOT NULL")]
		public int fkRelatedAreaId
		{
			get
			{
				return this._fkRelatedAreaId;
			}
			set
			{
				if ((this._fkRelatedAreaId != value))
				{
					this.OnfkRelatedAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkRelatedAreaId = value;
					this.SendPropertyChanged("fkRelatedAreaId");
					this.OnfkRelatedAreaIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.neighbouring_area")]
	public partial class neighbouring_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _neighbouring_areaId;
		
		private System.Nullable<int> _fkAreaId;
		
		private System.Nullable<int> _fkNeighbouringAreaId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onneighbouring_areaIdChanging(int value);
    partial void Onneighbouring_areaIdChanged();
    partial void OnfkAreaIdChanging(System.Nullable<int> value);
    partial void OnfkAreaIdChanged();
    partial void OnfkNeighbouringAreaIdChanging(System.Nullable<int> value);
    partial void OnfkNeighbouringAreaIdChanged();
    #endregion
		
		public neighbouring_area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neighbouring_areaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int neighbouring_areaId
		{
			get
			{
				return this._neighbouring_areaId;
			}
			set
			{
				if ((this._neighbouring_areaId != value))
				{
					this.Onneighbouring_areaIdChanging(value);
					this.SendPropertyChanging();
					this._neighbouring_areaId = value;
					this.SendPropertyChanged("neighbouring_areaId");
					this.Onneighbouring_areaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int")]
		public System.Nullable<int> fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this.OnfkAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkAreaId = value;
					this.SendPropertyChanged("fkAreaId");
					this.OnfkAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkNeighbouringAreaId", DbType="Int")]
		public System.Nullable<int> fkNeighbouringAreaId
		{
			get
			{
				return this._fkNeighbouringAreaId;
			}
			set
			{
				if ((this._fkNeighbouringAreaId != value))
				{
					this.OnfkNeighbouringAreaIdChanging(value);
					this.SendPropertyChanging();
					this._fkNeighbouringAreaId = value;
					this.SendPropertyChanged("fkNeighbouringAreaId");
					this.OnfkNeighbouringAreaIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.search")]
	public partial class search
	{
		
		private decimal _searchId;
		
		private decimal _searchCountry;
		
		private decimal _searchProvince;
		
		private decimal _searchRegion;
		
		private decimal _searchCity;
		
		private decimal _searchArea;
		
		private decimal _searchSuburb;
		
		private string _searchAreaName;
		
		private string _searchAreaParentName;
		
		private decimal _fkPropertyId;
		
		private System.Nullable<int> _fkAgentId;
		
		private int _fkBranchId;
		
		private System.Nullable<int> _fkAreaParentId;
		
		private int _fkAreaId;
		
		private int _fkCategoryId;
		
		private int _fkPropertyTypeId;
		
		private string _searchPropertyTypeName;
		
		private int _fkActionId;
		
		private System.Nullable<int> _fkGolfEstateId;
		
		private string _fkCity2010Id;
		
		private string _fkStadium2010Id;
		
		private string _searchReference;
		
		private System.Nullable<decimal> _searchPrice;
		
		private System.Nullable<decimal> _searchPriceAdjusted;
		
		private System.Nullable<int> _fkCurrencyId;
		
		private string _searchShortDescription;
		
		private string _searchRentalTerm;
		
		private System.Nullable<int> _searchBuildingSize;
		
		private System.Nullable<int> _searchBuildingUnit;
		
		private System.Nullable<decimal> _searchBuildingPerm2;
		
		private string _searchERFSize;
		
		private System.Nullable<int> _searchERFUnit;
		
		private System.Nullable<decimal> _searchLandPerm2;
		
		private System.Nullable<int> _searchBedrooms;
		
		private System.Nullable<int> _searchBathrooms;
		
		private System.Nullable<int> _searchGarages;
		
		private System.Nullable<int> _searchSecureParking;
		
		private System.Nullable<int> _searchReceptions;
		
		private string _searchImage;
		
		private System.Nullable<bool> _searchOnShow;
		
		private System.Nullable<bool> _searchPropertySold;
		
		private System.Nullable<bool> _searchPropertySeeffSelect;
		
		private System.Nullable<bool> _searchPropertyFnbQuicksell;
		
		private System.Nullable<System.DateTime> _searchPropertyLastUpdated;
		
		private string _searchAgentName;
		
		private string _searchBranchName;
		
		private string _searchPropertyGenieReference;
		
		private System.Nullable<System.DateTime> _searchPropertyGenieDateSuccess;
		
		private System.Nullable<bool> _searchProperty2010AccommodationRental;
		
		private System.Nullable<bool> _searchPropertyPOA;
		
		private System.Nullable<int> _searchPropertySleeps;
		
		private System.Nullable<bool> _searchPropertyIsPPPN;
		
		private string _searchPropertyBookingLink;
		
		private string _searchPropertyBookingLinkText;
		
		private System.Nullable<int> _searchKmFromStadium1;
		
		private System.Nullable<int> _searchKmFromStadium2;
		
		private System.Nullable<int> _searchKmFromStadium3;
		
		private System.Nullable<int> _searchKmFromStadium4;
		
		private System.Nullable<int> _searchKmFromStadium5;
		
		private System.Nullable<int> _searchKmFromStadium6;
		
		private System.Nullable<int> _searchKmFromStadium7;
		
		private System.Nullable<int> _searchKmFromStadium8;
		
		private System.Nullable<int> _searchKmFromStadium9;
		
		private System.Nullable<int> _searchKmFromStadium10;
		
		private int _searchPropertyESPServiceProvider;
		
		private System.Nullable<int> _propCntrolMandateId;
		
		private string _searchLongitude;
		
		private string _searchLicensee;
		
		private string _searchLatitude;
		
		public search()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchId", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal searchId
		{
			get
			{
				return this._searchId;
			}
			set
			{
				if ((this._searchId != value))
				{
					this._searchId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchCountry", DbType="Decimal(10,0) NOT NULL")]
		public decimal searchCountry
		{
			get
			{
				return this._searchCountry;
			}
			set
			{
				if ((this._searchCountry != value))
				{
					this._searchCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchProvince", DbType="Decimal(18,0) NOT NULL")]
		public decimal searchProvince
		{
			get
			{
				return this._searchProvince;
			}
			set
			{
				if ((this._searchProvince != value))
				{
					this._searchProvince = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchRegion", DbType="Decimal(18,0) NOT NULL")]
		public decimal searchRegion
		{
			get
			{
				return this._searchRegion;
			}
			set
			{
				if ((this._searchRegion != value))
				{
					this._searchRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchCity", DbType="Decimal(18,0) NOT NULL")]
		public decimal searchCity
		{
			get
			{
				return this._searchCity;
			}
			set
			{
				if ((this._searchCity != value))
				{
					this._searchCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchArea", DbType="Decimal(18,0) NOT NULL")]
		public decimal searchArea
		{
			get
			{
				return this._searchArea;
			}
			set
			{
				if ((this._searchArea != value))
				{
					this._searchArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchSuburb", DbType="Decimal(18,0) NOT NULL")]
		public decimal searchSuburb
		{
			get
			{
				return this._searchSuburb;
			}
			set
			{
				if ((this._searchSuburb != value))
				{
					this._searchSuburb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchAreaName", DbType="NVarChar(200)")]
		public string searchAreaName
		{
			get
			{
				return this._searchAreaName;
			}
			set
			{
				if ((this._searchAreaName != value))
				{
					this._searchAreaName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchAreaParentName", DbType="NVarChar(200)")]
		public string searchAreaParentName
		{
			get
			{
				return this._searchAreaParentName;
			}
			set
			{
				if ((this._searchAreaParentName != value))
				{
					this._searchAreaParentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkPropertyId", DbType="Decimal(18,0) NOT NULL")]
		public decimal fkPropertyId
		{
			get
			{
				return this._fkPropertyId;
			}
			set
			{
				if ((this._fkPropertyId != value))
				{
					this._fkPropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAgentId", DbType="Int")]
		public System.Nullable<int> fkAgentId
		{
			get
			{
				return this._fkAgentId;
			}
			set
			{
				if ((this._fkAgentId != value))
				{
					this._fkAgentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkBranchId", DbType="Int NOT NULL")]
		public int fkBranchId
		{
			get
			{
				return this._fkBranchId;
			}
			set
			{
				if ((this._fkBranchId != value))
				{
					this._fkBranchId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaParentId", DbType="Int")]
		public System.Nullable<int> fkAreaParentId
		{
			get
			{
				return this._fkAreaParentId;
			}
			set
			{
				if ((this._fkAreaParentId != value))
				{
					this._fkAreaParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkAreaId", DbType="Int NOT NULL")]
		public int fkAreaId
		{
			get
			{
				return this._fkAreaId;
			}
			set
			{
				if ((this._fkAreaId != value))
				{
					this._fkAreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCategoryId", DbType="Int NOT NULL")]
		public int fkCategoryId
		{
			get
			{
				return this._fkCategoryId;
			}
			set
			{
				if ((this._fkCategoryId != value))
				{
					this._fkCategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkPropertyTypeId", DbType="Int NOT NULL")]
		public int fkPropertyTypeId
		{
			get
			{
				return this._fkPropertyTypeId;
			}
			set
			{
				if ((this._fkPropertyTypeId != value))
				{
					this._fkPropertyTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyTypeName", DbType="NVarChar(200)")]
		public string searchPropertyTypeName
		{
			get
			{
				return this._searchPropertyTypeName;
			}
			set
			{
				if ((this._searchPropertyTypeName != value))
				{
					this._searchPropertyTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkActionId", DbType="Int NOT NULL")]
		public int fkActionId
		{
			get
			{
				return this._fkActionId;
			}
			set
			{
				if ((this._fkActionId != value))
				{
					this._fkActionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkGolfEstateId", DbType="Int")]
		public System.Nullable<int> fkGolfEstateId
		{
			get
			{
				return this._fkGolfEstateId;
			}
			set
			{
				if ((this._fkGolfEstateId != value))
				{
					this._fkGolfEstateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCity2010Id", DbType="VarChar(50)")]
		public string fkCity2010Id
		{
			get
			{
				return this._fkCity2010Id;
			}
			set
			{
				if ((this._fkCity2010Id != value))
				{
					this._fkCity2010Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkStadium2010Id", DbType="VarChar(50)")]
		public string fkStadium2010Id
		{
			get
			{
				return this._fkStadium2010Id;
			}
			set
			{
				if ((this._fkStadium2010Id != value))
				{
					this._fkStadium2010Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchReference", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string searchReference
		{
			get
			{
				return this._searchReference;
			}
			set
			{
				if ((this._searchReference != value))
				{
					this._searchReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPrice", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> searchPrice
		{
			get
			{
				return this._searchPrice;
			}
			set
			{
				if ((this._searchPrice != value))
				{
					this._searchPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPriceAdjusted", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> searchPriceAdjusted
		{
			get
			{
				return this._searchPriceAdjusted;
			}
			set
			{
				if ((this._searchPriceAdjusted != value))
				{
					this._searchPriceAdjusted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCurrencyId", DbType="Int")]
		public System.Nullable<int> fkCurrencyId
		{
			get
			{
				return this._fkCurrencyId;
			}
			set
			{
				if ((this._fkCurrencyId != value))
				{
					this._fkCurrencyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchShortDescription", DbType="NVarChar(3000)")]
		public string searchShortDescription
		{
			get
			{
				return this._searchShortDescription;
			}
			set
			{
				if ((this._searchShortDescription != value))
				{
					this._searchShortDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchRentalTerm", DbType="Char(20)")]
		public string searchRentalTerm
		{
			get
			{
				return this._searchRentalTerm;
			}
			set
			{
				if ((this._searchRentalTerm != value))
				{
					this._searchRentalTerm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBuildingSize", DbType="Int")]
		public System.Nullable<int> searchBuildingSize
		{
			get
			{
				return this._searchBuildingSize;
			}
			set
			{
				if ((this._searchBuildingSize != value))
				{
					this._searchBuildingSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBuildingUnit", DbType="Int")]
		public System.Nullable<int> searchBuildingUnit
		{
			get
			{
				return this._searchBuildingUnit;
			}
			set
			{
				if ((this._searchBuildingUnit != value))
				{
					this._searchBuildingUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBuildingPerm2", DbType="Money")]
		public System.Nullable<decimal> searchBuildingPerm2
		{
			get
			{
				return this._searchBuildingPerm2;
			}
			set
			{
				if ((this._searchBuildingPerm2 != value))
				{
					this._searchBuildingPerm2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchERFSize", DbType="NVarChar(50)")]
		public string searchERFSize
		{
			get
			{
				return this._searchERFSize;
			}
			set
			{
				if ((this._searchERFSize != value))
				{
					this._searchERFSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchERFUnit", DbType="Int")]
		public System.Nullable<int> searchERFUnit
		{
			get
			{
				return this._searchERFUnit;
			}
			set
			{
				if ((this._searchERFUnit != value))
				{
					this._searchERFUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchLandPerm2", DbType="Money")]
		public System.Nullable<decimal> searchLandPerm2
		{
			get
			{
				return this._searchLandPerm2;
			}
			set
			{
				if ((this._searchLandPerm2 != value))
				{
					this._searchLandPerm2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBedrooms", DbType="Int")]
		public System.Nullable<int> searchBedrooms
		{
			get
			{
				return this._searchBedrooms;
			}
			set
			{
				if ((this._searchBedrooms != value))
				{
					this._searchBedrooms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBathrooms", DbType="Int")]
		public System.Nullable<int> searchBathrooms
		{
			get
			{
				return this._searchBathrooms;
			}
			set
			{
				if ((this._searchBathrooms != value))
				{
					this._searchBathrooms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchGarages", DbType="Int")]
		public System.Nullable<int> searchGarages
		{
			get
			{
				return this._searchGarages;
			}
			set
			{
				if ((this._searchGarages != value))
				{
					this._searchGarages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchSecureParking", DbType="Int")]
		public System.Nullable<int> searchSecureParking
		{
			get
			{
				return this._searchSecureParking;
			}
			set
			{
				if ((this._searchSecureParking != value))
				{
					this._searchSecureParking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchReceptions", DbType="Int")]
		public System.Nullable<int> searchReceptions
		{
			get
			{
				return this._searchReceptions;
			}
			set
			{
				if ((this._searchReceptions != value))
				{
					this._searchReceptions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchImage", DbType="NVarChar(100)")]
		public string searchImage
		{
			get
			{
				return this._searchImage;
			}
			set
			{
				if ((this._searchImage != value))
				{
					this._searchImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchOnShow", DbType="Bit")]
		public System.Nullable<bool> searchOnShow
		{
			get
			{
				return this._searchOnShow;
			}
			set
			{
				if ((this._searchOnShow != value))
				{
					this._searchOnShow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertySold", DbType="Bit")]
		public System.Nullable<bool> searchPropertySold
		{
			get
			{
				return this._searchPropertySold;
			}
			set
			{
				if ((this._searchPropertySold != value))
				{
					this._searchPropertySold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertySeeffSelect", DbType="Bit")]
		public System.Nullable<bool> searchPropertySeeffSelect
		{
			get
			{
				return this._searchPropertySeeffSelect;
			}
			set
			{
				if ((this._searchPropertySeeffSelect != value))
				{
					this._searchPropertySeeffSelect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyFnbQuicksell", DbType="Bit")]
		public System.Nullable<bool> searchPropertyFnbQuicksell
		{
			get
			{
				return this._searchPropertyFnbQuicksell;
			}
			set
			{
				if ((this._searchPropertyFnbQuicksell != value))
				{
					this._searchPropertyFnbQuicksell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyLastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> searchPropertyLastUpdated
		{
			get
			{
				return this._searchPropertyLastUpdated;
			}
			set
			{
				if ((this._searchPropertyLastUpdated != value))
				{
					this._searchPropertyLastUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchAgentName", DbType="NVarChar(100)")]
		public string searchAgentName
		{
			get
			{
				return this._searchAgentName;
			}
			set
			{
				if ((this._searchAgentName != value))
				{
					this._searchAgentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchBranchName", DbType="NVarChar(100)")]
		public string searchBranchName
		{
			get
			{
				return this._searchBranchName;
			}
			set
			{
				if ((this._searchBranchName != value))
				{
					this._searchBranchName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyGenieReference", DbType="NVarChar(50)")]
		public string searchPropertyGenieReference
		{
			get
			{
				return this._searchPropertyGenieReference;
			}
			set
			{
				if ((this._searchPropertyGenieReference != value))
				{
					this._searchPropertyGenieReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyGenieDateSuccess", DbType="DateTime")]
		public System.Nullable<System.DateTime> searchPropertyGenieDateSuccess
		{
			get
			{
				return this._searchPropertyGenieDateSuccess;
			}
			set
			{
				if ((this._searchPropertyGenieDateSuccess != value))
				{
					this._searchPropertyGenieDateSuccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchProperty2010AccommodationRental", DbType="Bit")]
		public System.Nullable<bool> searchProperty2010AccommodationRental
		{
			get
			{
				return this._searchProperty2010AccommodationRental;
			}
			set
			{
				if ((this._searchProperty2010AccommodationRental != value))
				{
					this._searchProperty2010AccommodationRental = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyPOA", DbType="Bit")]
		public System.Nullable<bool> searchPropertyPOA
		{
			get
			{
				return this._searchPropertyPOA;
			}
			set
			{
				if ((this._searchPropertyPOA != value))
				{
					this._searchPropertyPOA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertySleeps", DbType="Int")]
		public System.Nullable<int> searchPropertySleeps
		{
			get
			{
				return this._searchPropertySleeps;
			}
			set
			{
				if ((this._searchPropertySleeps != value))
				{
					this._searchPropertySleeps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyIsPPPN", DbType="Bit")]
		public System.Nullable<bool> searchPropertyIsPPPN
		{
			get
			{
				return this._searchPropertyIsPPPN;
			}
			set
			{
				if ((this._searchPropertyIsPPPN != value))
				{
					this._searchPropertyIsPPPN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyBookingLink", DbType="NVarChar(250)")]
		public string searchPropertyBookingLink
		{
			get
			{
				return this._searchPropertyBookingLink;
			}
			set
			{
				if ((this._searchPropertyBookingLink != value))
				{
					this._searchPropertyBookingLink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyBookingLinkText", DbType="NVarChar(250)")]
		public string searchPropertyBookingLinkText
		{
			get
			{
				return this._searchPropertyBookingLinkText;
			}
			set
			{
				if ((this._searchPropertyBookingLinkText != value))
				{
					this._searchPropertyBookingLinkText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium1", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium1
		{
			get
			{
				return this._searchKmFromStadium1;
			}
			set
			{
				if ((this._searchKmFromStadium1 != value))
				{
					this._searchKmFromStadium1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium2", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium2
		{
			get
			{
				return this._searchKmFromStadium2;
			}
			set
			{
				if ((this._searchKmFromStadium2 != value))
				{
					this._searchKmFromStadium2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium3", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium3
		{
			get
			{
				return this._searchKmFromStadium3;
			}
			set
			{
				if ((this._searchKmFromStadium3 != value))
				{
					this._searchKmFromStadium3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium4", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium4
		{
			get
			{
				return this._searchKmFromStadium4;
			}
			set
			{
				if ((this._searchKmFromStadium4 != value))
				{
					this._searchKmFromStadium4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium5", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium5
		{
			get
			{
				return this._searchKmFromStadium5;
			}
			set
			{
				if ((this._searchKmFromStadium5 != value))
				{
					this._searchKmFromStadium5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium6", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium6
		{
			get
			{
				return this._searchKmFromStadium6;
			}
			set
			{
				if ((this._searchKmFromStadium6 != value))
				{
					this._searchKmFromStadium6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium7", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium7
		{
			get
			{
				return this._searchKmFromStadium7;
			}
			set
			{
				if ((this._searchKmFromStadium7 != value))
				{
					this._searchKmFromStadium7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium8", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium8
		{
			get
			{
				return this._searchKmFromStadium8;
			}
			set
			{
				if ((this._searchKmFromStadium8 != value))
				{
					this._searchKmFromStadium8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium9", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium9
		{
			get
			{
				return this._searchKmFromStadium9;
			}
			set
			{
				if ((this._searchKmFromStadium9 != value))
				{
					this._searchKmFromStadium9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchKmFromStadium10", DbType="Int")]
		public System.Nullable<int> searchKmFromStadium10
		{
			get
			{
				return this._searchKmFromStadium10;
			}
			set
			{
				if ((this._searchKmFromStadium10 != value))
				{
					this._searchKmFromStadium10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchPropertyESPServiceProvider", DbType="Int NOT NULL")]
		public int searchPropertyESPServiceProvider
		{
			get
			{
				return this._searchPropertyESPServiceProvider;
			}
			set
			{
				if ((this._searchPropertyESPServiceProvider != value))
				{
					this._searchPropertyESPServiceProvider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propCntrolMandateId", DbType="Int")]
		public System.Nullable<int> propCntrolMandateId
		{
			get
			{
				return this._propCntrolMandateId;
			}
			set
			{
				if ((this._propCntrolMandateId != value))
				{
					this._propCntrolMandateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchLongitude", DbType="VarChar(255)")]
		public string searchLongitude
		{
			get
			{
				return this._searchLongitude;
			}
			set
			{
				if ((this._searchLongitude != value))
				{
					this._searchLongitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchLicensee", DbType="VarChar(255)")]
		public string searchLicensee
		{
			get
			{
				return this._searchLicensee;
			}
			set
			{
				if ((this._searchLicensee != value))
				{
					this._searchLicensee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchLatitude", DbType="VarChar(255)")]
		public string searchLatitude
		{
			get
			{
				return this._searchLatitude;
			}
			set
			{
				if ((this._searchLatitude != value))
				{
					this._searchLatitude = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _categoryId;
		
		private string _categoryName;
		
		private System.Nullable<int> _categoryDisplayOrder;
		
		private System.Nullable<bool> _categoryCanRent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncategoryIdChanging(int value);
    partial void OncategoryIdChanged();
    partial void OncategoryNameChanging(string value);
    partial void OncategoryNameChanged();
    partial void OncategoryDisplayOrderChanging(System.Nullable<int> value);
    partial void OncategoryDisplayOrderChanged();
    partial void OncategoryCanRentChanging(System.Nullable<bool> value);
    partial void OncategoryCanRentChanged();
    #endregion
		
		public category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int categoryId
		{
			get
			{
				return this._categoryId;
			}
			set
			{
				if ((this._categoryId != value))
				{
					this.OncategoryIdChanging(value);
					this.SendPropertyChanging();
					this._categoryId = value;
					this.SendPropertyChanged("categoryId");
					this.OncategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryName", DbType="NVarChar(50)")]
		public string categoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				if ((this._categoryName != value))
				{
					this.OncategoryNameChanging(value);
					this.SendPropertyChanging();
					this._categoryName = value;
					this.SendPropertyChanged("categoryName");
					this.OncategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryDisplayOrder", DbType="Int")]
		public System.Nullable<int> categoryDisplayOrder
		{
			get
			{
				return this._categoryDisplayOrder;
			}
			set
			{
				if ((this._categoryDisplayOrder != value))
				{
					this.OncategoryDisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._categoryDisplayOrder = value;
					this.SendPropertyChanged("categoryDisplayOrder");
					this.OncategoryDisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryCanRent", DbType="Bit")]
		public System.Nullable<bool> categoryCanRent
		{
			get
			{
				return this._categoryCanRent;
			}
			set
			{
				if ((this._categoryCanRent != value))
				{
					this.OncategoryCanRentChanging(value);
					this.SendPropertyChanging();
					this._categoryCanRent = value;
					this.SendPropertyChanged("categoryCanRent");
					this.OncategoryCanRentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
