<?xml version="1.0" encoding="utf-8"?><Database Name="seeff" Class="SeeffDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=seeff;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="seeffConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.area" Member="areas">
    <Type Name="area">
      <Column Name="areaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="areaName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="areaParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkAreaTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nDisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaMap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sideMap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="areaImageMap" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="areaDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="areaPropertyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaResidentialPropertyBuyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaResidentialPropertyRentCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaCommercialPropertyBuyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaCommercialPropertyRentCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaDevelopementPropertyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaAgriculturalPropertyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kml_area" Member="kml_areas">
    <Type Name="kml_area">
      <Column Name="area_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="area_type" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="seq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kml_area_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AreaMap" Member="AreaMaps">
    <Type Name="AreaMap">
      <Column Name="areaMapId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sPath" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkAreaParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fkAreaTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.branch_area" Member="branch_areas">
    <Type Name="branch_area">
      <Column Name="branch_areaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkBranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.areaType" Member="areaTypes">
    <Type Name="areaType">
      <Column Name="areaTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="areaTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.branch" Member="branches">
    <Type Name="branch">
      <Column Name="branchId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="branchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="branchURL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="branchDialCode" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="branchTelephone" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="branchFax" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="branchCell" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="branchPostalAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="branchPhysicalAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="branchEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="branchContact" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="branchVax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fkBranchTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkCountryId" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="branchActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="branchParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branchCopy" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="branchSpeciality" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="branchOpeningHours" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="branchLicenseeInformation" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="branchSubscribedPropertyGenie" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="propCtrlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="virtualTour_width" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="virtualTour_height" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="branchViewOnly" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="updatedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="branchLatitude" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="branchLongitude" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.related_area" Member="related_areas">
    <Type Name="related_area">
      <Column Name="related_areaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkRelatedAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.neighbouring_area" Member="neighbouring_areas">
    <Type Name="neighbouring_area">
      <Column Name="neighbouring_areaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkNeighbouringAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.search" Member="searches">
    <Type Name="search">
      <Column Name="searchId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="searchCountry" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchProvince" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchRegion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchCity" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchArea" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchSuburb" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="searchAreaName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="searchAreaParentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fkPropertyId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="fkAgentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkAreaParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkPropertyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="searchPropertyTypeName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fkActionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkGolfEstateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkCity2010Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fkStadium2010Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="searchReference" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="searchPrice" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="searchPriceAdjusted" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="fkCurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchShortDescription" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="searchRentalTerm" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="searchBuildingSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchBuildingUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchBuildingPerm2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="searchERFSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="searchERFUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchLandPerm2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="searchBedrooms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchBathrooms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchGarages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchSecureParking" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchReceptions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchImage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="searchOnShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertySold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertySeeffSelect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertyFnbQuicksell" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertyLastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="searchAgentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="searchBranchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="searchPropertyGenieReference" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="searchPropertyGenieDateSuccess" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="searchProperty2010AccommodationRental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertyPOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertySleeps" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchPropertyIsPPPN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="searchPropertyBookingLink" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="searchPropertyBookingLinkText" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="searchKmFromStadium1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchKmFromStadium10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchPropertyESPServiceProvider" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="propCntrolMandateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchLongitude" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="searchLicensee" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="searchLatitude" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="categoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="categoryDisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="categoryCanRent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAreaPathMap" Method="GetAreaPathMap" IsComposable="true">
    <Parameter Name="propertyAreaId" Type="System.Int32" DbType="Int" />
    <Parameter Name="areaTypeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAreaParentName" Method="GetAreaParentName" IsComposable="true">
    <Parameter Name="areaIdVar" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
</Database>