CREATE TABLE [dbo].[bookings] (
    [bookingId]                    NUMERIC (19)  IDENTITY (1, 1) NOT NULL,
    [fkPropertyReference]          NUMERIC (10)  NULL,
    [bookingName]                  VARCHAR (100) NULL,
    [bookingLanguage]              VARCHAR (50)  NULL,
    [bookingContactTel]            VARCHAR (50)  NULL,
    [bookingEmail]                 VARCHAR (100) NULL,
    [bookingNumGuests]             INT           NULL,
    [bookingReserved]              TINYINT       CONSTRAINT [DF_bookings_bookingReserved] DEFAULT (0) NULL,
    [bookingDepositPaid]           TINYINT       CONSTRAINT [DF_bookings_bookingDepositPaid] DEFAULT (0) NULL,
    [bookingDepositPaidAmount]     INT           CONSTRAINT [DF_bookings_bookingDepositPaidAmount] DEFAULT (0) NULL,
    [bookingDepositDueDate]        DATETIME      NULL,
    [bookingDepositPaidDate]       DATETIME      NULL,
    [bookingSecondPaymentPaid]     TINYINT       CONSTRAINT [DF_bookings_bookingSecondPaymentMade] DEFAULT (0) NULL,
    [bookingSecondPaymentAmount]   INT           CONSTRAINT [DF_bookings_bookingSecondPaymentAmount] DEFAULT (0) NULL,
    [bookingSecondPaymentDueDate]  DATETIME      NULL,
    [bookingSecondPaymentPaidDate] DATETIME      NULL,
    [bookingFinalPaymentPaid]      TINYINT       CONSTRAINT [DF_bookings_bookingFinalPaymentMade] DEFAULT (0) NULL,
    [bookingFinalPaymentAmount]    INT           CONSTRAINT [DF_bookings_bookingFinalPaymentAmount] DEFAULT (0) NULL,
    [bookingFinalPaymentDueDate]   DATETIME      NULL,
    [bookingFinalPaymentPaidDate]  DATETIME      NULL,
    [bookingBreakageDepositAmount] INT           CONSTRAINT [DF_bookings_bookingBreakageDeposit] DEFAULT (0) NULL,
    [bookingBreakageDepositRepaid] TINYINT       CONSTRAINT [DF_bookings_bookingBreakageDepositRepaid] DEFAULT (0) NULL,
    [bookingDeleted]               TINYINT       CONSTRAINT [DF_bookings_bookingDeleted] DEFAULT (0) NULL,
    [bookingDeletedBy]             INT           NULL,
    [bookingDeletedDate]           DATETIME      NULL,
    [bookingAdded]                 DATETIME      NULL,
    CONSTRAINT [PK_bookings] PRIMARY KEY CLUSTERED ([bookingId] ASC)
);

