CREATE TABLE [dbo].[development] (
    [developmentId]               INT           IDENTITY (1, 1) NOT NULL,
    [developmentName]             VARCHAR (200) NULL,
    [fkAreaId]                    INT           NULL,
    [fkAgentId]                   INT           CONSTRAINT [DF_development_fkAgentId] DEFAULT ((-1)) NULL,
    [developmentWebReference]     INT           NULL,
    [developmentProvince]         INT           NULL,
    [developmentProvinceName]     VARCHAR (200) NULL,
    [developmentUrl]              VARCHAR (200) NULL,
    [developmentShortDescription] TEXT          NULL,
    [developmentLogo]             VARCHAR (200) NULL,
    [developmentLandscapePic]     VARCHAR (200) NULL,
    [developmentOverviewSearch]   TEXT          NULL,
    [developmentOverview]         TEXT          NULL,
    [developmentLocation]         TEXT          NULL,
    [developmentFeatures]         TEXT          NULL,
    [developmentPriceExtra]       VARCHAR (200) NULL,
    [developmentPrice]            MONEY         NULL,
    [developmentImageRoot]        VARCHAR (200) NULL,
    [developmentOverviewPic]      VARCHAR (200) NULL,
    [developmentLocationPic]      VARCHAR (200) NULL,
    [developmentFeaturePic]       VARCHAR (200) NULL,
    [developmentSketch1]          VARCHAR (200) NULL,
    [developmentSketch1Dim]       VARCHAR (50)  NULL,
    [developmentSketch2]          VARCHAR (200) NULL,
    [developmentSketch2Dim]       VARCHAR (50)  NULL,
    [developmentSketch3]          VARCHAR (200) NULL,
    [developmentSketch3Dim]       VARCHAR (50)  NULL,
    [developmentSketch4]          VARCHAR (200) NULL,
    [developmentSketch4Dim]       VARCHAR (50)  NULL,
    [developmentFloorPlan1]       VARCHAR (200) NULL,
    [developmentFloorPlan1Name]   VARCHAR (200) NULL,
    [developmentFloorPlan1Dim]    VARCHAR (50)  NULL,
    [developmentFloorPlan2]       VARCHAR (200) NULL,
    [developmentFloorPlan2Name]   VARCHAR (200) NULL,
    [developmentFloorPlan2Dim]    VARCHAR (50)  NULL,
    [developmentFloorPlan3]       VARCHAR (200) NULL,
    [developmentFloorPlan3Name]   VARCHAR (200) NULL,
    [developmentFloorPlan3Dim]    VARCHAR (50)  NULL,
    [developmentActive]           BIT           NULL,
    CONSTRAINT [PK_development] PRIMARY KEY CLUSTERED ([developmentId] ASC) WITH (FILLFACTOR = 90)
);

