CREATE TABLE [dbo].[property_bkp] (
    [property_bkp_id]                   INT             IDENTITY (1, 1) NOT NULL,
    [propertyId]                        NUMERIC (18)    NOT NULL,
    [propertyReference]                 NUMERIC (18)    NOT NULL,
    [propertyReferenceOld]              NUMERIC (18)    NULL,
    [fkAgentId]                         INT             CONSTRAINT [DF_property_bkp_fkAgentId] DEFAULT (0) NULL,
    [fkBranchId]                        INT             NULL,
    [fkAreaId]                          INT             NULL,
    [fkCategoryId]                      INT             NOT NULL,
    [fkPropertyTypeId]                  INT             NULL,
    [fkActionId]                        INT             NULL,
    [propertyPrice]                     MONEY           CONSTRAINT [DF_property_bkp_propertyPrice] DEFAULT (0) NOT NULL,
    [fkCurrencyId]                      INT             NULL,
    [propertyShortDescription]          TEXT            NULL,
    [propertyFullDescription]           TEXT            NULL,
    [propertyBuildingSize]              INT             NULL,
    [propertyBuildingUnit]              INT             CONSTRAINT [DF_property_bkp_propertyBuildingUnit] DEFAULT (0) NULL,
    [propertyERFNumber]                 NVARCHAR (50)   NULL,
    [propertyERFSize]                   NVARCHAR (50)   NULL,
    [propertyERFUnit]                   INT             CONSTRAINT [DF_property_bkp_propertyERFUnit] DEFAULT (0) NULL,
    [propertyPriceNeg]                  BIT             NULL,
    [propertyRatesAndTaxes]             MONEY           CONSTRAINT [DF_property_bkp_propertyratesAndTaxes] DEFAULT (0) NOT NULL,
    [propertyRentalTerm]                CHAR (20)       CONSTRAINT [DF_property_bkp_propertyRentalTerm] DEFAULT ('n/a') NULL,
    [propertyMandate]                   CHAR (20)       CONSTRAINT [DF_property_bkp_propertyMandate] DEFAULT ('n/a') NULL,
    [propertySellerName]                NVARCHAR (50)   NULL,
    [propertyOccupationDate]            DATETIME        NULL,
    [propertyActive]                    BIT             CONSTRAINT [DF_property_bkp_propertyActive] DEFAULT (1) NOT NULL,
    [propertyVirtualTour]               NVARCHAR (20)   NULL,
    [propertyVirtualTourURL]            NVARCHAR (255)  NULL,
    [propertyVirtualTourX]              NVARCHAR (5)    NULL,
    [propertyVirtualTourY]              NVARCHAR (5)    NULL,
    [propertyVirtualTourGalleryURL]     NVARCHAR (255)  CONSTRAINT [DF_property_bkp_propertyVirtualTourOffsiteURL] DEFAULT ('') NULL,
    [propertyVirtualTourGalleryURLText] NVARCHAR (255)  CONSTRAINT [DF_property_bkp_propertyVirtualTourDescription] DEFAULT ('') NULL,
    [propertyCreated]                   DATETIME        CONSTRAINT [DF_property_bkp_propertyCreated] DEFAULT (getdate()) NOT NULL,
    [propertyLastUpdated]               DATETIME        NULL,
    [propertyDateSold]                  DATETIME        NULL,
    [propertySellingPrice]              MONEY           CONSTRAINT [DF_property_bkp_propertySellingPrice] DEFAULT (0) NOT NULL,
    [fkSellerId]                        INT             CONSTRAINT [DF_property_bkp_fkCompetitorId] DEFAULT (0) NOT NULL,
    [propertyAddress]                   NVARCHAR (500)  NULL,
    [propertyTelephoneAreaCode]         NVARCHAR (50)   NULL,
    [propertyTelephone]                 NVARCHAR (50)   NULL,
    [propertyAdditionalFeatures]        NVARCHAR (3000) NULL,
    [propertyOnShow]                    BIT             CONSTRAINT [DF_property_bkp_propertyActive1] DEFAULT (0) NOT NULL,
    [propertyOnShowDirections]          NVARCHAR (2000) NULL,
    [propertyOnShowTime]                NVARCHAR (50)   NULL,
    [propertyFeatured]                  BIT             CONSTRAINT [DF_property_bkp_propertyFeatured] DEFAULT (0) NOT NULL,
    [propertySeeffSelect]               BIT             CONSTRAINT [DF_property_bkp_propertySeeffSelect] DEFAULT (0) NULL,
    [propertLastEditedBy]               INT             CONSTRAINT [DF_property_bkp_propertLastEditedBy] DEFAULT (0) NOT NULL,
    [propertyVetted]                    BIT             CONSTRAINT [DF_property_bkp_vetted] DEFAULT (0) NULL,
    [propertyGenieSyndicated]           TINYINT         CONSTRAINT [DF_property_bkp_propertyGenieSyndicated] DEFAULT (0) NULL,
    [propertyGenieExpiryDate]           DATETIME        NULL,
    [propertyGenieReference]            NVARCHAR (50)   NULL,
    [propertyGenieSuccessDate]          DATETIME        NULL,
    [propertyFnbQuicksell]              BIT             CONSTRAINT [DF_property_bkp_propertyFnbQuicksell] DEFAULT (0) NULL,
    CONSTRAINT [PK_property_bkp] PRIMARY KEY CLUSTERED ([property_bkp_id] ASC) WITH (FILLFACTOR = 90)
);

