CREATE TABLE [dbo].[search] (
    [searchId]                              NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [searchCountry]                         NUMERIC (10)    DEFAULT ((-1)) NOT NULL,
    [searchProvince]                        NUMERIC (18)    DEFAULT ((-1)) NOT NULL,
    [searchRegion]                          NUMERIC (18)    DEFAULT ((-1)) NOT NULL,
    [searchCity]                            NUMERIC (18)    DEFAULT ((-1)) NOT NULL,
    [searchArea]                            NUMERIC (18)    DEFAULT ((-1)) NOT NULL,
    [searchSuburb]                          NUMERIC (18)    DEFAULT ((-1)) NOT NULL,
    [searchAreaName]                        NVARCHAR (200)  NULL,
    [searchAreaParentName]                  NVARCHAR (200)  NULL,
    [fkPropertyId]                          NUMERIC (18)    NOT NULL,
    [fkAgentId]                             INT             NULL,
    [fkBranchId]                            INT             NOT NULL,
    [fkAreaParentId]                        INT             NULL,
    [fkAreaId]                              INT             NOT NULL,
    [fkCategoryId]                          INT             NOT NULL,
    [fkPropertyTypeId]                      INT             NOT NULL,
    [searchPropertyTypeName]                NVARCHAR (200)  NULL,
    [fkActionId]                            INT             NOT NULL,
    [fkGolfEstateId]                        INT             DEFAULT ((0)) NULL,
    [fkCity2010Id]                          VARCHAR (50)    NULL,
    [fkStadium2010Id]                       VARCHAR (50)    NULL,
    [searchReference]                       VARCHAR (20)    NOT NULL,
    [searchPrice]                           NUMERIC (19, 4) NULL,
    [searchPriceAdjusted]                   NUMERIC (19, 4) NULL,
    [fkCurrencyId]                          INT             NULL,
    [searchShortDescription]                NVARCHAR (3000) NULL,
    [searchRentalTerm]                      CHAR (20)       NULL,
    [searchBuildingSize]                    INT             NULL,
    [searchBuildingUnit]                    INT             NULL,
    [searchBuildingPerm2]                   MONEY           NULL,
    [searchERFSize]                         NVARCHAR (50)   DEFAULT ((0)) NULL,
    [searchERFUnit]                         INT             NULL,
    [searchLandPerm2]                       MONEY           DEFAULT ((0)) NULL,
    [searchBedrooms]                        INT             DEFAULT ((0)) NULL,
    [searchBathrooms]                       INT             DEFAULT ((0)) NULL,
    [searchGarages]                         INT             DEFAULT ((0)) NULL,
    [searchSecureParking]                   INT             DEFAULT ((0)) NULL,
    [searchReceptions]                      INT             DEFAULT ((0)) NULL,
    [searchImage]                           NVARCHAR (100)  NULL,
    [searchOnShow]                          BIT             NULL,
    [searchPropertySold]                    BIT             DEFAULT ((0)) NULL,
    [searchPropertySeeffSelect]             BIT             NULL,
    [searchPropertyFnbQuicksell]            BIT             NULL,
    [searchPropertyLastUpdated]             DATETIME        NULL,
    [searchAgentName]                       NVARCHAR (100)  NULL,
    [searchBranchName]                      NVARCHAR (100)  NULL,
    [searchPropertyGenieReference]          NVARCHAR (50)   NULL,
    [searchPropertyGenieDateSuccess]        DATETIME        NULL,
    [searchProperty2010AccommodationRental] BIT             NULL,
    [searchPropertyPOA]                     BIT             NULL,
    [searchPropertySleeps]                  INT             NULL,
    [searchPropertyIsPPPN]                  BIT             NULL,
    [searchPropertyBookingLink]             NVARCHAR (250)  NULL,
    [searchPropertyBookingLinkText]         NVARCHAR (250)  NULL,
    [searchKmFromStadium1]                  INT             NULL,
    [searchKmFromStadium2]                  INT             NULL,
    [searchKmFromStadium3]                  INT             NULL,
    [searchKmFromStadium4]                  INT             NULL,
    [searchKmFromStadium5]                  INT             NULL,
    [searchKmFromStadium6]                  INT             NULL,
    [searchKmFromStadium7]                  INT             NULL,
    [searchKmFromStadium8]                  INT             NULL,
    [searchKmFromStadium9]                  INT             NULL,
    [searchKmFromStadium10]                 INT             NULL,
    [searchPropertyESPServiceProvider]      INT             DEFAULT ((0)) NOT NULL,
    [propCntrolMandateId]                   INT             NULL,
    [searchLongitude]                       VARCHAR (255)   NULL,
    [searchLicensee]                        VARCHAR (255)   NULL,
    [searchLatitude]                        VARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([searchId] ASC)
);

