//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingProject.DracoreETLConsumerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubAccountReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenVerifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestTime {
            get {
                return this.RequestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTimeField, value) != true)) {
                    this.RequestTimeField = value;
                    this.RaisePropertyChanged("RequestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubAccountReference {
            get {
                return this.SubAccountReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubAccountReferenceField, value) != true)) {
                    this.SubAccountReferenceField = value;
                    this.RaisePropertyChanged("SubAccountReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenVerify {
            get {
                return this.TokenVerifyField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenVerifyField, value) != true)) {
                    this.TokenVerifyField = value;
                    this.RaisePropertyChanged("TokenVerify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseSearchOfCompany_Pd39ncJe", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProspectingProject.DracoreETLConsumerService.CompanySearch))]
    public partial class BaseSearchOfCompany_Pd39ncJe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.DracoreETLConsumerService.SearchResultType ResultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.DracoreETLConsumerService.Company[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.DracoreETLConsumerService.SearchResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.DracoreETLConsumerService.Company[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanySearch", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    public partial class CompanySearch : ProspectingProject.DracoreETLConsumerService.BaseSearchOfCompany_Pd39ncJe {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResultType", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    public enum SearchResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatchesFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultipleMatchesFound = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = -1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.DracoreETLConsumerService.Director[] DirectorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.DracoreETLConsumerService.Director[] Directors {
            get {
                return this.DirectorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorsField, value) != true)) {
                    this.DirectorsField = value;
                    this.RaisePropertyChanged("Directors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationNumber {
            get {
                return this.RegistrationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationNumberField, value) != true)) {
                    this.RegistrationNumberField = value;
                    this.RaisePropertyChanged("RegistrationNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Director", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    public partial class Director : ProspectingProject.DracoreETLConsumerService.BasePerson {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateAppointedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateResignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAppointed {
            get {
                return this.DateAppointedField;
            }
            set {
                if ((this.DateAppointedField.Equals(value) != true)) {
                    this.DateAppointedField = value;
                    this.RaisePropertyChanged("DateAppointed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateResigned {
            get {
                return this.DateResignedField;
            }
            set {
                if ((this.DateResignedField.Equals(value) != true)) {
                    this.DateResignedField = value;
                    this.RaisePropertyChanged("DateResigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasePerson", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProspectingProject.DracoreETLConsumerService.Director))]
    public partial class BasePerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeceasedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProspectingProject.DracoreETLConsumerService.GenderEnum GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deceased {
            get {
                return this.DeceasedField;
            }
            set {
                if ((this.DeceasedField.Equals(value) != true)) {
                    this.DeceasedField = value;
                    this.RaisePropertyChanged("Deceased");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNames {
            get {
                return this.FirstNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamesField, value) != true)) {
                    this.FirstNamesField = value;
                    this.RaisePropertyChanged("FirstNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProspectingProject.DracoreETLConsumerService.GenderEnum Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber {
            get {
                return this.IdentityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityNumberField, value) != true)) {
                    this.IdentityNumberField = value;
                    this.RaisePropertyChanged("IdentityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderEnum", Namespace="http://schemas.datacontract.org/2004/07/DC.Models")]
    public enum GenderEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DracoreETLConsumerService.IDracoreDataService")]
    public interface IDracoreDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDracoreDataService/SearchCompanies", ReplyAction="http://tempuri.org/IDracoreDataService/SearchCompaniesResponse")]
        ProspectingProject.DracoreETLConsumerService.CompanySearch SearchCompanies(ProspectingProject.DracoreETLConsumerService.Token token, string reference, string companyName, string registrationNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDracoreDataService/SearchCompanies", ReplyAction="http://tempuri.org/IDracoreDataService/SearchCompaniesResponse")]
        System.Threading.Tasks.Task<ProspectingProject.DracoreETLConsumerService.CompanySearch> SearchCompaniesAsync(ProspectingProject.DracoreETLConsumerService.Token token, string reference, string companyName, string registrationNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDracoreDataServiceChannel : ProspectingProject.DracoreETLConsumerService.IDracoreDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DracoreDataServiceClient : System.ServiceModel.ClientBase<ProspectingProject.DracoreETLConsumerService.IDracoreDataService>, ProspectingProject.DracoreETLConsumerService.IDracoreDataService {
        
        public DracoreDataServiceClient() {
        }
        
        public DracoreDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DracoreDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DracoreDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DracoreDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProspectingProject.DracoreETLConsumerService.CompanySearch SearchCompanies(ProspectingProject.DracoreETLConsumerService.Token token, string reference, string companyName, string registrationNumber) {
            return base.Channel.SearchCompanies(token, reference, companyName, registrationNumber);
        }
        
        public System.Threading.Tasks.Task<ProspectingProject.DracoreETLConsumerService.CompanySearch> SearchCompaniesAsync(ProspectingProject.DracoreETLConsumerService.Token token, string reference, string companyName, string registrationNumber) {
            return base.Channel.SearchCompaniesAsync(token, reference, companyName, registrationNumber);
        }
    }
}
