//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int pk_address_id { get; set; }
        public int fk_client_id { get; set; }
        public int fk_address_type_id { get; set; }
        public string address1 { get; set; }
        public int fk_area_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public int is_active_status { get; set; }
        public string postal_code { get; set; }
    
        public virtual address_type address_type { get; set; }
        public virtual client client { get; set; }
    }
}
