//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bossEntities : DbContext
    {
        public bossEntities()
            : base("name=bossEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<license> license { get; set; }
        public virtual DbSet<user_preference> user_preference { get; set; }
        public virtual DbSet<user_preference_type> user_preference_type { get; set; }
        public virtual DbSet<user_registration> user_registration { get; set; }
        public virtual DbSet<license_branches> license_branches { get; set; }
    }
}
