//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_sync_log
    {
        public int client_sync_log_id { get; set; }
        public int contact_person_id { get; set; }
        public Nullable<System.Guid> user_guid { get; set; }
        public System.DateTime date_time { get; set; }
        public bool synchronised { get; set; }
    
        public virtual prospecting_contact_person prospecting_contact_person { get; set; }
    }
}
