//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_type
    {
        public int pk_client_type_id { get; set; }
        public int fk_client_id { get; set; }
        public int fk_client_type_description_id { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<bool> is_active_status { get; set; }
    
        public virtual client client { get; set; }
        public virtual client_type_description client_type_description { get; set; }
    }
}
