//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clientEntities : DbContext
    {
        public clientEntities()
            : base("name=clientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<address_type> address_type { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<client_activity> client_activity { get; set; }
        public virtual DbSet<client_agent> client_agent { get; set; }
        public virtual DbSet<client_agent_role_type> client_agent_role_type { get; set; }
        public virtual DbSet<client_audit> client_audit { get; set; }
        public virtual DbSet<client_branch> client_branch { get; set; }
        public virtual DbSet<client_contact_source> client_contact_source { get; set; }
        public virtual DbSet<client_contact_status> client_contact_status { get; set; }
        public virtual DbSet<client_ethnic_group> client_ethnic_group { get; set; }
        public virtual DbSet<client_gender> client_gender { get; set; }
        public virtual DbSet<client_license> client_license { get; set; }
        public virtual DbSet<client_relationship> client_relationship { get; set; }
        public virtual DbSet<client_relationship_type> client_relationship_type { get; set; }
        public virtual DbSet<client_system> client_system { get; set; }
        public virtual DbSet<client_system_relationship> client_system_relationship { get; set; }
        public virtual DbSet<client_title> client_title { get; set; }
        public virtual DbSet<client_type> client_type { get; set; }
        public virtual DbSet<client_type_description> client_type_description { get; set; }
        public virtual DbSet<client_user> client_user { get; set; }
        public virtual DbSet<contact_details> contact_details { get; set; }
        public virtual DbSet<contact_details_location_type> contact_details_location_type { get; set; }
        public virtual DbSet<contact_details_type> contact_details_type { get; set; }
        public virtual DbSet<contact_source_type> contact_source_type { get; set; }
        public virtual DbSet<contact_status_type> contact_status_type { get; set; }
        public virtual DbSet<country_code> country_code { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<marital_status_type> marital_status_type { get; set; }
        public virtual DbSet<religion> religion { get; set; }
        public virtual DbSet<search_client> search_client { get; set; }
    }
}
