//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.address = new HashSet<address>();
            this.client_activity = new HashSet<client_activity>();
            this.client_contact_status = new HashSet<client_contact_status>();
            this.client_contact_source = new HashSet<client_contact_source>();
            this.client_agent = new HashSet<client_agent>();
            this.client_audit = new HashSet<client_audit>();
            this.client_branch = new HashSet<client_branch>();
            this.client_license = new HashSet<client_license>();
            this.client_relationship = new HashSet<client_relationship>();
            this.client_relationship1 = new HashSet<client_relationship>();
            this.client_type = new HashSet<client_type>();
            this.client_user = new HashSet<client_user>();
            this.contact_details = new HashSet<contact_details>();
            this.search_client = new HashSet<search_client>();
        }
    
        public int pk_client_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string preferred_name { get; set; }
        public string identity_number { get; set; }
        public string passport_number { get; set; }
        public Nullable<int> title { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> ethnic_group { get; set; }
        public string occupation { get; set; }
        public Nullable<int> fk_marital_status_type_id { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> identified { get; set; }
        public Nullable<System.DateTime> identified_date { get; set; }
        public Nullable<bool> blocked { get; set; }
        public Nullable<System.DateTime> blocked_date { get; set; }
        public Nullable<int> fk_language_id { get; set; }
        public Nullable<int> fk_religion_id { get; set; }
        public Nullable<int> fk_citizenship { get; set; }
        public Nullable<int> fk_country_of_residence { get; set; }
        public Nullable<int> preferred_language { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> deceased_status { get; set; }
        public bool popi_opt_in { get; set; }
        public bool phone_call_opt_in { get; set; }
        public bool email_opt_in { get; set; }
        public bool sms_opt_in { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address> address { get; set; }
        public virtual client_ethnic_group client_ethnic_group { get; set; }
        public virtual client_ethnic_group client_ethnic_group1 { get; set; }
        public virtual country_code country_code { get; set; }
        public virtual country_code country_code1 { get; set; }
        public virtual country_code country_code2 { get; set; }
        public virtual country_code country_code3 { get; set; }
        public virtual client_gender client_gender { get; set; }
        public virtual client_gender client_gender1 { get; set; }
        public virtual language language { get; set; }
        public virtual language language1 { get; set; }
        public virtual client_title client_title { get; set; }
        public virtual client_title client_title1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_activity> client_activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_contact_status> client_contact_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_contact_source> client_contact_source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_agent> client_agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_audit> client_audit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_branch> client_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_license> client_license { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_relationship> client_relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_relationship> client_relationship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_type> client_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_user> client_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_details> contact_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<search_client> search_client { get; set; }
    }
}
