//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_details
    {
        public int pk_contact_details_id { get; set; }
        public int fk_client_id { get; set; }
        public int fk_contact_details_type_id { get; set; }
        public int fk_contact_details_location_type_id { get; set; }
        public string contact_details_value { get; set; }
        public Nullable<bool> is_primary_contact { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<bool> is_active_status { get; set; }
        public Nullable<int> fk_country_code { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
    
        public virtual client client { get; set; }
        public virtual country_code country_code { get; set; }
        public virtual contact_details_location_type contact_details_location_type { get; set; }
        public virtual contact_details_type contact_details_type { get; set; }
    }
}
