//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public int error_log_id { get; set; }
        public int target_application { get; set; }
        public string friendly_error_msg { get; set; }
        public string exception_string { get; set; }
        public Nullable<System.Guid> user { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual client_system client_system { get; set; }
    }
}
