//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public int license_id { get; set; }
        public string license_name { get; set; }
        public string region { get; set; }
        public string sub_region { get; set; }
        public string sub_license_name { get; set; }
        public int registration_id { get; set; }
        public string manager { get; set; }
        public bool residential { get; set; }
        public bool rental { get; set; }
        public bool commercial { get; set; }
        public bool agricultural { get; set; }
        public bool developments { get; set; }
        public bool distressed { get; set; }
        public string top_twenty_region { get; set; }
        public string Status { get; set; }
        public string datasheet_link { get; set; }
        public Nullable<int> percentage_quota { get; set; }
        public Nullable<int> sales_referral_residential_id { get; set; }
        public Nullable<int> rentals_referrals_residential_id { get; set; }
        public Nullable<int> sales_referral_commercial_id { get; set; }
        public Nullable<int> rentals_referrals_commercial_id { get; set; }
        public Nullable<int> sales_referral_agricultural_id { get; set; }
        public Nullable<int> rentals_referrals_agricultural_id { get; set; }
        public Nullable<int> sales_referral_developments_id { get; set; }
        public Nullable<int> rentals_referrals_developments_id { get; set; }
        public bool icas { get; set; }
        public bool debt_remedy { get; set; }
        public Nullable<int> cluster { get; set; }
        public string google_region_key { get; set; }
        public string google_licsense_key { get; set; }
        public string google_statutory_submissions { get; set; }
        public Nullable<int> agent_target { get; set; }
        public string academy_institution { get; set; }
        public Nullable<int> division { get; set; }
    }
}
