//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class lightstone_call_log
    {
        public int lightstone_call_log_id { get; set; }
        public System.Guid user { get; set; }
        public System.DateTime date_time { get; set; }
        public string call_location_src { get; set; }
        public string search_inputs { get; set; }
    }
}
