//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecting_person_property_relationship
    {
        public int person_property_relationship_id { get; set; }
        public int contact_person_id { get; set; }
        public int prospecting_property_id { get; set; }
        public int relationship_to_property { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
    
        public virtual prospecting_contact_person prospecting_contact_person { get; set; }
        public virtual prospecting_property prospecting_property { get; set; }
    }
}
