//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecting_contact_detail
    {
        public int prospecting_contact_detail_id { get; set; }
        public int contact_detail_type { get; set; }
        public int contact_person_id { get; set; }
        public string contact_detail { get; set; }
        public Nullable<int> intl_dialing_code_id { get; set; }
        public Nullable<int> eleventh_digit { get; set; }
        public bool is_primary_contact { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
    
        public virtual prospecting_contact_person prospecting_contact_person { get; set; }
        public virtual prospecting_area_dialing_code prospecting_area_dialing_code { get; set; }
        public virtual prospecting_contact_detail_type prospecting_contact_detail_type { get; set; }
    }
}
