//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecting_area_dialing_code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prospecting_area_dialing_code()
        {
            this.prospecting_contact_detail = new HashSet<prospecting_contact_detail>();
        }
    
        public int prospecting_area_dialing_code_id { get; set; }
        public int dialing_code_id { get; set; }
        public string code_desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospecting_contact_detail> prospecting_contact_detail { get; set; }
    }
}
