//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seeff_prospectingEntities : DbContext
    {
        public seeff_prospectingEntities()
            : base("name=seeff_prospectingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity_log> activity_log { get; set; }
        public virtual DbSet<prospecting_contact_detail> prospecting_contact_detail { get; set; }
        public virtual DbSet<sms_communications_log> sms_communications_log { get; set; }
        public virtual DbSet<prospecting_contact_person> prospecting_contact_person { get; set; }
        public virtual DbSet<prospecting_area_dialing_code> prospecting_area_dialing_code { get; set; }
        public virtual DbSet<client_sync_log> client_sync_log { get; set; }
        public virtual DbSet<prospecting_person_property_relationship> prospecting_person_property_relationship { get; set; }
        public virtual DbSet<exception_log> exception_log { get; set; }
        public virtual DbSet<email_communications_log> email_communications_log { get; set; }
        public virtual DbSet<activity_type> activity_type { get; set; }
        public virtual DbSet<activity_followup_type> activity_followup_type { get; set; }
        public virtual DbSet<prospecting_property> prospecting_property { get; set; }
        public virtual DbSet<prospecting_contact_detail_type> prospecting_contact_detail_type { get; set; }
        public virtual DbSet<communications_status> communications_status { get; set; }
        public virtual DbSet<lightstone_call_log> lightstone_call_log { get; set; }
    }
}
