//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecting_contact_person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prospecting_contact_person()
        {
            this.activity_log = new HashSet<activity_log>();
            this.prospecting_contact_detail = new HashSet<prospecting_contact_detail>();
            this.sms_communications_log = new HashSet<sms_communications_log>();
            this.client_sync_log = new HashSet<client_sync_log>();
            this.prospecting_person_property_relationship = new HashSet<prospecting_person_property_relationship>();
            this.email_communications_log = new HashSet<email_communications_log>();
        }
    
        public int contact_person_id { get; set; }
        public Nullable<int> person_title { get; set; }
        public string person_gender { get; set; }
        public string id_number { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string job_title { get; set; }
        public Nullable<int> propcntrl_buyer_id { get; set; }
        public Nullable<bool> referral_network { get; set; }
        public Nullable<bool> investor { get; set; }
        public bool is_popi_restricted { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string comments_notes { get; set; }
        public string deceased_status { get; set; }
        public string age_group { get; set; }
        public string location { get; set; }
        public string marital_status { get; set; }
        public string home_ownership { get; set; }
        public string directorship { get; set; }
        public string physical_address { get; set; }
        public string employer { get; set; }
        public string occupation { get; set; }
        public string bureau_adverse_indicator { get; set; }
        public string citizenship { get; set; }
        public bool optout_emails { get; set; }
        public bool optout_sms { get; set; }
        public bool do_not_contact { get; set; }
        public int email_contactability_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_log> activity_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospecting_contact_detail> prospecting_contact_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sms_communications_log> sms_communications_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_sync_log> client_sync_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prospecting_person_property_relationship> prospecting_person_property_relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email_communications_log> email_communications_log { get; set; }
    }
}
