//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEFF_Deeds_Monthly
    {
        public Nullable<int> LS_Area_id { get; set; }
        public string Seeff_LIC_Area { get; set; }
        public int property_id { get; set; }
        public string iregdate { get; set; }
        public Nullable<decimal> ipurchdate { get; set; }
        public string TITLE_DEED_NO { get; set; }
        public Nullable<decimal> NON_GAR_PROPS_ON_TITLE { get; set; }
        public Nullable<decimal> PURCH_PRICE { get; set; }
        public string erf_key { get; set; }
        public string ea_code { get; set; }
        public string suburb { get; set; }
        public string munic_name { get; set; }
        public string province { get; set; }
        public string property_type { get; set; }
        public string ss_fh { get; set; }
        public string PROPERTY_CURRENTLY_IN_PVT_HANDS { get; set; }
        public string PRIVATE_REGISTRATION { get; set; }
        public string bonded_transfer { get; set; }
        public Nullable<int> suburb_id { get; set; }
        public Nullable<decimal> erf_size { get; set; }
        public string BUYER_NAME { get; set; }
        public string SELLER_NAME { get; set; }
        public string SECT_SCHEME_NAME { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<bool> LS_ResFlg { get; set; }
        public string Estate_Name { get; set; }
        public string BUYER_NAME_2 { get; set; }
        public string MultiBuyer { get; set; }
        public string SEEFF_SUBURB { get; set; }
        public Nullable<int> Seeff_Suburb_ID { get; set; }
        public string Seeff_Suburb_Type { get; set; }
        public Nullable<int> Seeff_LIC_ID { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
    }
}
