//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_communications_log
    {
        public int sms_communications_log_id { get; set; }
        public System.Guid batch_id { get; set; }
        public string batch_friendly_name { get; set; }
        public int batch_activity_type_id { get; set; }
        public Nullable<long> activity_log_id { get; set; }
        public Nullable<long> followup_activity_id { get; set; }
        public System.Guid created_by_user_guid { get; set; }
        public System.DateTime created_datetime { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public int target_contact_person_id { get; set; }
        public string target_cellphone_no { get; set; }
        public int target_lightstone_property_id { get; set; }
        public int status { get; set; }
        public string api_tracking_id { get; set; }
        public string api_delivery_status { get; set; }
        public string msg_body_or_link_id { get; set; }
        public string reply { get; set; }
        public string error_msg { get; set; }
        public Nullable<int> user_business_unit_id { get; set; }
    
        public virtual activity_log activity_log { get; set; }
        public virtual activity_log activity_log1 { get; set; }
        public virtual prospecting_contact_person prospecting_contact_person { get; set; }
        public virtual activity_type activity_type { get; set; }
        public virtual communications_status communications_status { get; set; }
    }
}
