//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_registration()
        {
            this.user_preference = new HashSet<user_preference>();
        }
    
        public long registration_id { get; set; }
        public string title { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public int branch_id { get; set; }
        public string user_email_address { get; set; }
        public string user_private_email_address { get; set; }
        public string user_preferred_name { get; set; }
        public string user_cellphone_no { get; set; }
        public string user_office_no { get; set; }
        public string user_fax_no { get; set; }
        public string designation { get; set; }
        public string user_password { get; set; }
        public string user_guid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string reminder { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> licensee_id { get; set; }
        public string confirmation { get; set; }
        public string achiever { get; set; }
        public Nullable<bool> achiever_life_time { get; set; }
        public Nullable<bool> achiever_platinum { get; set; }
        public Nullable<bool> achiever_ordinary { get; set; }
        public string id_no { get; set; }
        public string fidelity_fund_no { get; set; }
        public string physical_address_1 { get; set; }
        public string physical_address_2 { get; set; }
        public string physical_town_city { get; set; }
        public string physical_province { get; set; }
        public string physical_code { get; set; }
        public string postal_address_1 { get; set; }
        public string postal_address_2 { get; set; }
        public string postal_town_city { get; set; }
        public string postal_province { get; set; }
        public string postal_code { get; set; }
        public string smart_account { get; set; }
        public string pop_account { get; set; }
        public Nullable<System.DateTime> acc_anniversary { get; set; }
        public string home_language { get; set; }
        public Nullable<System.DateTime> fidelity_fund_expiry { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string region { get; set; }
        public string sub_region { get; set; }
        public string gender { get; set; }
        public string sa_citizen { get; set; }
        public Nullable<int> fkAgentId { get; set; }
        public bool license_referral_contact { get; set; }
        public bool birthday_wish { get; set; }
        public bool birthday_display { get; set; }
        public bool icas { get; set; }
        public Nullable<int> search_group { get; set; }
        public string ms_area_permissions { get; set; }
        public bool smart_pass_email_summary { get; set; }
        public string prospecting_areas { get; set; }
        public decimal prospecting_credits { get; set; }
        public bool prospecting_contact_sync { get; set; }
        public bool active { get; set; }
        public bool prospecting_control { get; set; }
        public bool compliance_access { get; set; }
        public Nullable<System.Guid> session_key { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<int> deleted_by { get; set; }
        public string license_control { get; set; }
        public bool prospecting_communication { get; set; }
        public bool mapping { get; set; }
        public bool trust_lookup { get; set; }
        public Nullable<decimal> target_at_seven_perc { get; set; }
        public bool prospecting_comm_override { get; set; }
        public Nullable<int> fk_ethnic_group_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_preference> user_preference { get; set; }
    }
}
