//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectingTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_preference
    {
        public int pk_user_preference_id { get; set; }
        public int fk_user_preference_type_id { get; set; }
        public long fk_user_registration_id { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual user_preference_type user_preference_type { get; set; }
        public virtual user_registration user_registration { get; set; }
    }
}
