#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "boss")]
    public partial class BossDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void Insertuser_registration(user_registration instance);
        partial void Updateuser_registration(user_registration instance);
        partial void Deleteuser_registration(user_registration instance);
        #endregion

        public BossDataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BossDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BossDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BossDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<user_registration> user_registrations
        {
            get
            {
                return this.GetTable<user_registration>();
            }
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.user_auth")]
        public int user_auth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string user_guid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "UniqueIdentifier")] System.Nullable<System.Guid> session_key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string app)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_guid, session_key, app);
            return ((int)(result.ReturnValue));
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.user_registration")]
    public partial class user_registration : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private long _registration_id;

        private string _title;

        private string _user_name;

        private string _user_surname;

        private int _branch_id;

        private string _user_email_address;

        private string _user_private_email_address;

        private string _user_preferred_name;

        private string _user_cellphone_no;

        private string _user_office_no;

        private string _user_fax_no;

        private string _designation;

        private string _user_password;

        private string _user_guid;

        private System.DateTime _created_date;

        private System.Nullable<System.DateTime> _update_date;

        private string _reminder;

        private System.Nullable<System.DateTime> _DOB;

        private System.Nullable<int> _licensee_id;

        private string _confirmation;

        private string _achiever;

        private System.Nullable<bool> _achiever_life_time;

        private System.Nullable<bool> _achiever_platinum;

        private System.Nullable<bool> _achiever_ordinary;

        private string _id_no;

        private string _fidelity_fund_no;

        private string _physical_address_1;

        private string _physical_address_2;

        private string _physical_town_city;

        private string _physical_province;

        private string _physical_code;

        private string _postal_address_1;

        private string _postal_address_2;

        private string _postal_town_city;

        private string _postal_province;

        private string _postal_code;

        private System.Nullable<char> _smart_account;

        private System.Nullable<char> _pop_account;

        private System.Nullable<System.DateTime> _acc_anniversary;

        private string _home_language;

        private System.Nullable<System.DateTime> _fidelity_fund_expiry;

        private System.Nullable<System.DateTime> _start_date;

        private string _region;

        private string _sub_region;

        private string _gender;

        private string _sa_citizen;

        private System.Nullable<int> _fkAgentId;

        private bool _license_referral_contact;

        private bool _birthday_wish;

        private bool _birthday_display;

        private bool _icas;

        private System.Nullable<int> _search_group;

        private string _ms_area_permissions;

        private bool _smart_pass_email_summary;

        private string _prospecting_areas;

        private decimal _prospecting_credits;

        private bool _prospecting_contact_sync;

        private bool _active;

        private bool _prospecting_control;

        private bool _compliance_access;

        private System.Nullable<System.Guid> _session_key;

        private System.Nullable<System.DateTime> _deleted_date;

        private System.Nullable<int> _deleted_by;

        private string _license_control;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void Onregistration_idChanging(long value);
        partial void Onregistration_idChanged();
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        partial void Onuser_nameChanging(string value);
        partial void Onuser_nameChanged();
        partial void Onuser_surnameChanging(string value);
        partial void Onuser_surnameChanged();
        partial void Onbranch_idChanging(int value);
        partial void Onbranch_idChanged();
        partial void Onuser_email_addressChanging(string value);
        partial void Onuser_email_addressChanged();
        partial void Onuser_private_email_addressChanging(string value);
        partial void Onuser_private_email_addressChanged();
        partial void Onuser_preferred_nameChanging(string value);
        partial void Onuser_preferred_nameChanged();
        partial void Onuser_cellphone_noChanging(string value);
        partial void Onuser_cellphone_noChanged();
        partial void Onuser_office_noChanging(string value);
        partial void Onuser_office_noChanged();
        partial void Onuser_fax_noChanging(string value);
        partial void Onuser_fax_noChanged();
        partial void OndesignationChanging(string value);
        partial void OndesignationChanged();
        partial void Onuser_passwordChanging(string value);
        partial void Onuser_passwordChanged();
        partial void Onuser_guidChanging(string value);
        partial void Onuser_guidChanged();
        partial void Oncreated_dateChanging(System.DateTime value);
        partial void Oncreated_dateChanged();
        partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
        partial void Onupdate_dateChanged();
        partial void OnreminderChanging(string value);
        partial void OnreminderChanged();
        partial void OnDOBChanging(System.Nullable<System.DateTime> value);
        partial void OnDOBChanged();
        partial void Onlicensee_idChanging(System.Nullable<int> value);
        partial void Onlicensee_idChanged();
        partial void OnconfirmationChanging(string value);
        partial void OnconfirmationChanged();
        partial void OnachieverChanging(string value);
        partial void OnachieverChanged();
        partial void Onachiever_life_timeChanging(System.Nullable<bool> value);
        partial void Onachiever_life_timeChanged();
        partial void Onachiever_platinumChanging(System.Nullable<bool> value);
        partial void Onachiever_platinumChanged();
        partial void Onachiever_ordinaryChanging(System.Nullable<bool> value);
        partial void Onachiever_ordinaryChanged();
        partial void Onid_noChanging(string value);
        partial void Onid_noChanged();
        partial void Onfidelity_fund_noChanging(string value);
        partial void Onfidelity_fund_noChanged();
        partial void Onphysical_address_1Changing(string value);
        partial void Onphysical_address_1Changed();
        partial void Onphysical_address_2Changing(string value);
        partial void Onphysical_address_2Changed();
        partial void Onphysical_town_cityChanging(string value);
        partial void Onphysical_town_cityChanged();
        partial void Onphysical_provinceChanging(string value);
        partial void Onphysical_provinceChanged();
        partial void Onphysical_codeChanging(string value);
        partial void Onphysical_codeChanged();
        partial void Onpostal_address_1Changing(string value);
        partial void Onpostal_address_1Changed();
        partial void Onpostal_address_2Changing(string value);
        partial void Onpostal_address_2Changed();
        partial void Onpostal_town_cityChanging(string value);
        partial void Onpostal_town_cityChanged();
        partial void Onpostal_provinceChanging(string value);
        partial void Onpostal_provinceChanged();
        partial void Onpostal_codeChanging(string value);
        partial void Onpostal_codeChanged();
        partial void Onsmart_accountChanging(System.Nullable<char> value);
        partial void Onsmart_accountChanged();
        partial void Onpop_accountChanging(System.Nullable<char> value);
        partial void Onpop_accountChanged();
        partial void Onacc_anniversaryChanging(System.Nullable<System.DateTime> value);
        partial void Onacc_anniversaryChanged();
        partial void Onhome_languageChanging(string value);
        partial void Onhome_languageChanged();
        partial void Onfidelity_fund_expiryChanging(System.Nullable<System.DateTime> value);
        partial void Onfidelity_fund_expiryChanged();
        partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
        partial void Onstart_dateChanged();
        partial void OnregionChanging(string value);
        partial void OnregionChanged();
        partial void Onsub_regionChanging(string value);
        partial void Onsub_regionChanged();
        partial void OngenderChanging(string value);
        partial void OngenderChanged();
        partial void Onsa_citizenChanging(string value);
        partial void Onsa_citizenChanged();
        partial void OnfkAgentIdChanging(System.Nullable<int> value);
        partial void OnfkAgentIdChanged();
        partial void Onlicense_referral_contactChanging(bool value);
        partial void Onlicense_referral_contactChanged();
        partial void Onbirthday_wishChanging(bool value);
        partial void Onbirthday_wishChanged();
        partial void Onbirthday_displayChanging(bool value);
        partial void Onbirthday_displayChanged();
        partial void OnicasChanging(bool value);
        partial void OnicasChanged();
        partial void Onsearch_groupChanging(System.Nullable<int> value);
        partial void Onsearch_groupChanged();
        partial void Onms_area_permissionsChanging(string value);
        partial void Onms_area_permissionsChanged();
        partial void Onsmart_pass_email_summaryChanging(bool value);
        partial void Onsmart_pass_email_summaryChanged();
        partial void Onprospecting_areasChanging(string value);
        partial void Onprospecting_areasChanged();
        partial void Onprospecting_creditsChanging(decimal value);
        partial void Onprospecting_creditsChanged();
        partial void Onprospecting_contact_syncChanging(bool value);
        partial void Onprospecting_contact_syncChanged();
        partial void OnactiveChanging(bool value);
        partial void OnactiveChanged();
        partial void Onprospecting_controlChanging(bool value);
        partial void Onprospecting_controlChanged();
        partial void Oncompliance_accessChanging(bool value);
        partial void Oncompliance_accessChanged();
        partial void Onsession_keyChanging(System.Nullable<System.Guid> value);
        partial void Onsession_keyChanged();
        partial void Ondeleted_dateChanging(System.Nullable<System.DateTime> value);
        partial void Ondeleted_dateChanged();
        partial void Ondeleted_byChanging(System.Nullable<int> value);
        partial void Ondeleted_byChanged();
        partial void Onlicense_controlChanging(string value);
        partial void Onlicense_controlChanged();
        #endregion

        public user_registration()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_registration_id", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public long registration_id
        {
            get
            {
                return this._registration_id;
            }
            set
            {
                if ((this._registration_id != value))
                {
                    this.Onregistration_idChanging(value);
                    this.SendPropertyChanging();
                    this._registration_id = value;
                    this.SendPropertyChanged("registration_id");
                    this.Onregistration_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_title", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                if ((this._title != value))
                {
                    this.OntitleChanging(value);
                    this.SendPropertyChanging();
                    this._title = value;
                    this.SendPropertyChanged("title");
                    this.OntitleChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_name", DbType = "VarChar(250) NOT NULL", CanBeNull = false)]
        public string user_name
        {
            get
            {
                return this._user_name;
            }
            set
            {
                if ((this._user_name != value))
                {
                    this.Onuser_nameChanging(value);
                    this.SendPropertyChanging();
                    this._user_name = value;
                    this.SendPropertyChanged("user_name");
                    this.Onuser_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_surname", DbType = "VarChar(250) NOT NULL", CanBeNull = false)]
        public string user_surname
        {
            get
            {
                return this._user_surname;
            }
            set
            {
                if ((this._user_surname != value))
                {
                    this.Onuser_surnameChanging(value);
                    this.SendPropertyChanging();
                    this._user_surname = value;
                    this.SendPropertyChanged("user_surname");
                    this.Onuser_surnameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_branch_id", DbType = "Int NOT NULL")]
        public int branch_id
        {
            get
            {
                return this._branch_id;
            }
            set
            {
                if ((this._branch_id != value))
                {
                    this.Onbranch_idChanging(value);
                    this.SendPropertyChanging();
                    this._branch_id = value;
                    this.SendPropertyChanged("branch_id");
                    this.Onbranch_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_email_address", DbType = "VarChar(250)")]
        public string user_email_address
        {
            get
            {
                return this._user_email_address;
            }
            set
            {
                if ((this._user_email_address != value))
                {
                    this.Onuser_email_addressChanging(value);
                    this.SendPropertyChanging();
                    this._user_email_address = value;
                    this.SendPropertyChanged("user_email_address");
                    this.Onuser_email_addressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_private_email_address", DbType = "VarChar(250)")]
        public string user_private_email_address
        {
            get
            {
                return this._user_private_email_address;
            }
            set
            {
                if ((this._user_private_email_address != value))
                {
                    this.Onuser_private_email_addressChanging(value);
                    this.SendPropertyChanging();
                    this._user_private_email_address = value;
                    this.SendPropertyChanged("user_private_email_address");
                    this.Onuser_private_email_addressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_preferred_name", DbType = "VarChar(250)")]
        public string user_preferred_name
        {
            get
            {
                return this._user_preferred_name;
            }
            set
            {
                if ((this._user_preferred_name != value))
                {
                    this.Onuser_preferred_nameChanging(value);
                    this.SendPropertyChanging();
                    this._user_preferred_name = value;
                    this.SendPropertyChanged("user_preferred_name");
                    this.Onuser_preferred_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_cellphone_no", DbType = "VarChar(11) NOT NULL", CanBeNull = false)]
        public string user_cellphone_no
        {
            get
            {
                return this._user_cellphone_no;
            }
            set
            {
                if ((this._user_cellphone_no != value))
                {
                    this.Onuser_cellphone_noChanging(value);
                    this.SendPropertyChanging();
                    this._user_cellphone_no = value;
                    this.SendPropertyChanged("user_cellphone_no");
                    this.Onuser_cellphone_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_office_no", DbType = "VarChar(11)")]
        public string user_office_no
        {
            get
            {
                return this._user_office_no;
            }
            set
            {
                if ((this._user_office_no != value))
                {
                    this.Onuser_office_noChanging(value);
                    this.SendPropertyChanging();
                    this._user_office_no = value;
                    this.SendPropertyChanged("user_office_no");
                    this.Onuser_office_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_fax_no", DbType = "VarChar(11)")]
        public string user_fax_no
        {
            get
            {
                return this._user_fax_no;
            }
            set
            {
                if ((this._user_fax_no != value))
                {
                    this.Onuser_fax_noChanging(value);
                    this.SendPropertyChanging();
                    this._user_fax_no = value;
                    this.SendPropertyChanged("user_fax_no");
                    this.Onuser_fax_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_designation", DbType = "VarChar(200) NOT NULL", CanBeNull = false)]
        public string designation
        {
            get
            {
                return this._designation;
            }
            set
            {
                if ((this._designation != value))
                {
                    this.OndesignationChanging(value);
                    this.SendPropertyChanging();
                    this._designation = value;
                    this.SendPropertyChanged("designation");
                    this.OndesignationChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_password", DbType = "VarChar(50)")]
        public string user_password
        {
            get
            {
                return this._user_password;
            }
            set
            {
                if ((this._user_password != value))
                {
                    this.Onuser_passwordChanging(value);
                    this.SendPropertyChanging();
                    this._user_password = value;
                    this.SendPropertyChanged("user_password");
                    this.Onuser_passwordChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_user_guid", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string user_guid
        {
            get
            {
                return this._user_guid;
            }
            set
            {
                if ((this._user_guid != value))
                {
                    this.Onuser_guidChanging(value);
                    this.SendPropertyChanging();
                    this._user_guid = value;
                    this.SendPropertyChanged("user_guid");
                    this.Onuser_guidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_date", DbType = "DateTime NOT NULL")]
        public System.DateTime created_date
        {
            get
            {
                return this._created_date;
            }
            set
            {
                if ((this._created_date != value))
                {
                    this.Oncreated_dateChanging(value);
                    this.SendPropertyChanging();
                    this._created_date = value;
                    this.SendPropertyChanged("created_date");
                    this.Oncreated_dateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_update_date", DbType = "DateTime")]
        public System.Nullable<System.DateTime> update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                if ((this._update_date != value))
                {
                    this.Onupdate_dateChanging(value);
                    this.SendPropertyChanging();
                    this._update_date = value;
                    this.SendPropertyChanged("update_date");
                    this.Onupdate_dateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_reminder", DbType = "VarChar(50)")]
        public string reminder
        {
            get
            {
                return this._reminder;
            }
            set
            {
                if ((this._reminder != value))
                {
                    this.OnreminderChanging(value);
                    this.SendPropertyChanging();
                    this._reminder = value;
                    this.SendPropertyChanged("reminder");
                    this.OnreminderChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOB", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DOB
        {
            get
            {
                return this._DOB;
            }
            set
            {
                if ((this._DOB != value))
                {
                    this.OnDOBChanging(value);
                    this.SendPropertyChanging();
                    this._DOB = value;
                    this.SendPropertyChanged("DOB");
                    this.OnDOBChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_licensee_id", DbType = "Int")]
        public System.Nullable<int> licensee_id
        {
            get
            {
                return this._licensee_id;
            }
            set
            {
                if ((this._licensee_id != value))
                {
                    this.Onlicensee_idChanging(value);
                    this.SendPropertyChanging();
                    this._licensee_id = value;
                    this.SendPropertyChanged("licensee_id");
                    this.Onlicensee_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_confirmation", DbType = "VarChar(1)")]
        public string confirmation
        {
            get
            {
                return this._confirmation;
            }
            set
            {
                if ((this._confirmation != value))
                {
                    this.OnconfirmationChanging(value);
                    this.SendPropertyChanging();
                    this._confirmation = value;
                    this.SendPropertyChanged("confirmation");
                    this.OnconfirmationChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_achiever", DbType = "VarChar(1)")]
        public string achiever
        {
            get
            {
                return this._achiever;
            }
            set
            {
                if ((this._achiever != value))
                {
                    this.OnachieverChanging(value);
                    this.SendPropertyChanging();
                    this._achiever = value;
                    this.SendPropertyChanged("achiever");
                    this.OnachieverChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_achiever_life_time", DbType = "Bit")]
        public System.Nullable<bool> achiever_life_time
        {
            get
            {
                return this._achiever_life_time;
            }
            set
            {
                if ((this._achiever_life_time != value))
                {
                    this.Onachiever_life_timeChanging(value);
                    this.SendPropertyChanging();
                    this._achiever_life_time = value;
                    this.SendPropertyChanged("achiever_life_time");
                    this.Onachiever_life_timeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_achiever_platinum", DbType = "Bit")]
        public System.Nullable<bool> achiever_platinum
        {
            get
            {
                return this._achiever_platinum;
            }
            set
            {
                if ((this._achiever_platinum != value))
                {
                    this.Onachiever_platinumChanging(value);
                    this.SendPropertyChanging();
                    this._achiever_platinum = value;
                    this.SendPropertyChanged("achiever_platinum");
                    this.Onachiever_platinumChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_achiever_ordinary", DbType = "Bit")]
        public System.Nullable<bool> achiever_ordinary
        {
            get
            {
                return this._achiever_ordinary;
            }
            set
            {
                if ((this._achiever_ordinary != value))
                {
                    this.Onachiever_ordinaryChanging(value);
                    this.SendPropertyChanging();
                    this._achiever_ordinary = value;
                    this.SendPropertyChanged("achiever_ordinary");
                    this.Onachiever_ordinaryChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id_no", DbType = "VarChar(13)")]
        public string id_no
        {
            get
            {
                return this._id_no;
            }
            set
            {
                if ((this._id_no != value))
                {
                    this.Onid_noChanging(value);
                    this.SendPropertyChanging();
                    this._id_no = value;
                    this.SendPropertyChanged("id_no");
                    this.Onid_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_fidelity_fund_no", DbType = "VarChar(20)")]
        public string fidelity_fund_no
        {
            get
            {
                return this._fidelity_fund_no;
            }
            set
            {
                if ((this._fidelity_fund_no != value))
                {
                    this.Onfidelity_fund_noChanging(value);
                    this.SendPropertyChanging();
                    this._fidelity_fund_no = value;
                    this.SendPropertyChanged("fidelity_fund_no");
                    this.Onfidelity_fund_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_physical_address_1", DbType = "VarChar(150)")]
        public string physical_address_1
        {
            get
            {
                return this._physical_address_1;
            }
            set
            {
                if ((this._physical_address_1 != value))
                {
                    this.Onphysical_address_1Changing(value);
                    this.SendPropertyChanging();
                    this._physical_address_1 = value;
                    this.SendPropertyChanged("physical_address_1");
                    this.Onphysical_address_1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_physical_address_2", DbType = "VarChar(150)")]
        public string physical_address_2
        {
            get
            {
                return this._physical_address_2;
            }
            set
            {
                if ((this._physical_address_2 != value))
                {
                    this.Onphysical_address_2Changing(value);
                    this.SendPropertyChanging();
                    this._physical_address_2 = value;
                    this.SendPropertyChanged("physical_address_2");
                    this.Onphysical_address_2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_physical_town_city", DbType = "VarChar(150)")]
        public string physical_town_city
        {
            get
            {
                return this._physical_town_city;
            }
            set
            {
                if ((this._physical_town_city != value))
                {
                    this.Onphysical_town_cityChanging(value);
                    this.SendPropertyChanging();
                    this._physical_town_city = value;
                    this.SendPropertyChanged("physical_town_city");
                    this.Onphysical_town_cityChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_physical_province", DbType = "VarChar(100)")]
        public string physical_province
        {
            get
            {
                return this._physical_province;
            }
            set
            {
                if ((this._physical_province != value))
                {
                    this.Onphysical_provinceChanging(value);
                    this.SendPropertyChanging();
                    this._physical_province = value;
                    this.SendPropertyChanged("physical_province");
                    this.Onphysical_provinceChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_physical_code", DbType = "VarChar(10)")]
        public string physical_code
        {
            get
            {
                return this._physical_code;
            }
            set
            {
                if ((this._physical_code != value))
                {
                    this.Onphysical_codeChanging(value);
                    this.SendPropertyChanging();
                    this._physical_code = value;
                    this.SendPropertyChanged("physical_code");
                    this.Onphysical_codeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_postal_address_1", DbType = "VarChar(150)")]
        public string postal_address_1
        {
            get
            {
                return this._postal_address_1;
            }
            set
            {
                if ((this._postal_address_1 != value))
                {
                    this.Onpostal_address_1Changing(value);
                    this.SendPropertyChanging();
                    this._postal_address_1 = value;
                    this.SendPropertyChanged("postal_address_1");
                    this.Onpostal_address_1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_postal_address_2", DbType = "VarChar(150)")]
        public string postal_address_2
        {
            get
            {
                return this._postal_address_2;
            }
            set
            {
                if ((this._postal_address_2 != value))
                {
                    this.Onpostal_address_2Changing(value);
                    this.SendPropertyChanging();
                    this._postal_address_2 = value;
                    this.SendPropertyChanged("postal_address_2");
                    this.Onpostal_address_2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_postal_town_city", DbType = "VarChar(150)")]
        public string postal_town_city
        {
            get
            {
                return this._postal_town_city;
            }
            set
            {
                if ((this._postal_town_city != value))
                {
                    this.Onpostal_town_cityChanging(value);
                    this.SendPropertyChanging();
                    this._postal_town_city = value;
                    this.SendPropertyChanged("postal_town_city");
                    this.Onpostal_town_cityChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_postal_province", DbType = "VarChar(100)")]
        public string postal_province
        {
            get
            {
                return this._postal_province;
            }
            set
            {
                if ((this._postal_province != value))
                {
                    this.Onpostal_provinceChanging(value);
                    this.SendPropertyChanging();
                    this._postal_province = value;
                    this.SendPropertyChanged("postal_province");
                    this.Onpostal_provinceChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_postal_code", DbType = "VarChar(50)")]
        public string postal_code
        {
            get
            {
                return this._postal_code;
            }
            set
            {
                if ((this._postal_code != value))
                {
                    this.Onpostal_codeChanging(value);
                    this.SendPropertyChanging();
                    this._postal_code = value;
                    this.SendPropertyChanged("postal_code");
                    this.Onpostal_codeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_smart_account", DbType = "Char(1)")]
        public System.Nullable<char> smart_account
        {
            get
            {
                return this._smart_account;
            }
            set
            {
                if ((this._smart_account != value))
                {
                    this.Onsmart_accountChanging(value);
                    this.SendPropertyChanging();
                    this._smart_account = value;
                    this.SendPropertyChanged("smart_account");
                    this.Onsmart_accountChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_pop_account", DbType = "Char(1)")]
        public System.Nullable<char> pop_account
        {
            get
            {
                return this._pop_account;
            }
            set
            {
                if ((this._pop_account != value))
                {
                    this.Onpop_accountChanging(value);
                    this.SendPropertyChanging();
                    this._pop_account = value;
                    this.SendPropertyChanged("pop_account");
                    this.Onpop_accountChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_acc_anniversary", DbType = "DateTime")]
        public System.Nullable<System.DateTime> acc_anniversary
        {
            get
            {
                return this._acc_anniversary;
            }
            set
            {
                if ((this._acc_anniversary != value))
                {
                    this.Onacc_anniversaryChanging(value);
                    this.SendPropertyChanging();
                    this._acc_anniversary = value;
                    this.SendPropertyChanged("acc_anniversary");
                    this.Onacc_anniversaryChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_home_language", DbType = "VarChar(100)")]
        public string home_language
        {
            get
            {
                return this._home_language;
            }
            set
            {
                if ((this._home_language != value))
                {
                    this.Onhome_languageChanging(value);
                    this.SendPropertyChanging();
                    this._home_language = value;
                    this.SendPropertyChanged("home_language");
                    this.Onhome_languageChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_fidelity_fund_expiry", DbType = "DateTime")]
        public System.Nullable<System.DateTime> fidelity_fund_expiry
        {
            get
            {
                return this._fidelity_fund_expiry;
            }
            set
            {
                if ((this._fidelity_fund_expiry != value))
                {
                    this.Onfidelity_fund_expiryChanging(value);
                    this.SendPropertyChanging();
                    this._fidelity_fund_expiry = value;
                    this.SendPropertyChanged("fidelity_fund_expiry");
                    this.Onfidelity_fund_expiryChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_start_date", DbType = "DateTime")]
        public System.Nullable<System.DateTime> start_date
        {
            get
            {
                return this._start_date;
            }
            set
            {
                if ((this._start_date != value))
                {
                    this.Onstart_dateChanging(value);
                    this.SendPropertyChanging();
                    this._start_date = value;
                    this.SendPropertyChanged("start_date");
                    this.Onstart_dateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_region", DbType = "VarChar(100)")]
        public string region
        {
            get
            {
                return this._region;
            }
            set
            {
                if ((this._region != value))
                {
                    this.OnregionChanging(value);
                    this.SendPropertyChanging();
                    this._region = value;
                    this.SendPropertyChanged("region");
                    this.OnregionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_sub_region", DbType = "VarChar(100)")]
        public string sub_region
        {
            get
            {
                return this._sub_region;
            }
            set
            {
                if ((this._sub_region != value))
                {
                    this.Onsub_regionChanging(value);
                    this.SendPropertyChanging();
                    this._sub_region = value;
                    this.SendPropertyChanged("sub_region");
                    this.Onsub_regionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_gender", DbType = "VarChar(1)")]
        public string gender
        {
            get
            {
                return this._gender;
            }
            set
            {
                if ((this._gender != value))
                {
                    this.OngenderChanging(value);
                    this.SendPropertyChanging();
                    this._gender = value;
                    this.SendPropertyChanged("gender");
                    this.OngenderChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_sa_citizen", DbType = "VarChar(1)")]
        public string sa_citizen
        {
            get
            {
                return this._sa_citizen;
            }
            set
            {
                if ((this._sa_citizen != value))
                {
                    this.Onsa_citizenChanging(value);
                    this.SendPropertyChanging();
                    this._sa_citizen = value;
                    this.SendPropertyChanged("sa_citizen");
                    this.Onsa_citizenChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_fkAgentId", DbType = "Int")]
        public System.Nullable<int> fkAgentId
        {
            get
            {
                return this._fkAgentId;
            }
            set
            {
                if ((this._fkAgentId != value))
                {
                    this.OnfkAgentIdChanging(value);
                    this.SendPropertyChanging();
                    this._fkAgentId = value;
                    this.SendPropertyChanged("fkAgentId");
                    this.OnfkAgentIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_referral_contact", DbType = "Bit NOT NULL")]
        public bool license_referral_contact
        {
            get
            {
                return this._license_referral_contact;
            }
            set
            {
                if ((this._license_referral_contact != value))
                {
                    this.Onlicense_referral_contactChanging(value);
                    this.SendPropertyChanging();
                    this._license_referral_contact = value;
                    this.SendPropertyChanged("license_referral_contact");
                    this.Onlicense_referral_contactChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_birthday_wish", DbType = "Bit NOT NULL")]
        public bool birthday_wish
        {
            get
            {
                return this._birthday_wish;
            }
            set
            {
                if ((this._birthday_wish != value))
                {
                    this.Onbirthday_wishChanging(value);
                    this.SendPropertyChanging();
                    this._birthday_wish = value;
                    this.SendPropertyChanged("birthday_wish");
                    this.Onbirthday_wishChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_birthday_display", DbType = "Bit NOT NULL")]
        public bool birthday_display
        {
            get
            {
                return this._birthday_display;
            }
            set
            {
                if ((this._birthday_display != value))
                {
                    this.Onbirthday_displayChanging(value);
                    this.SendPropertyChanging();
                    this._birthday_display = value;
                    this.SendPropertyChanged("birthday_display");
                    this.Onbirthday_displayChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_icas", DbType = "Bit NOT NULL")]
        public bool icas
        {
            get
            {
                return this._icas;
            }
            set
            {
                if ((this._icas != value))
                {
                    this.OnicasChanging(value);
                    this.SendPropertyChanging();
                    this._icas = value;
                    this.SendPropertyChanged("icas");
                    this.OnicasChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_search_group", DbType = "Int")]
        public System.Nullable<int> search_group
        {
            get
            {
                return this._search_group;
            }
            set
            {
                if ((this._search_group != value))
                {
                    this.Onsearch_groupChanging(value);
                    this.SendPropertyChanging();
                    this._search_group = value;
                    this.SendPropertyChanged("search_group");
                    this.Onsearch_groupChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ms_area_permissions", DbType = "VarChar(MAX)")]
        public string ms_area_permissions
        {
            get
            {
                return this._ms_area_permissions;
            }
            set
            {
                if ((this._ms_area_permissions != value))
                {
                    this.Onms_area_permissionsChanging(value);
                    this.SendPropertyChanging();
                    this._ms_area_permissions = value;
                    this.SendPropertyChanged("ms_area_permissions");
                    this.Onms_area_permissionsChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_smart_pass_email_summary", DbType = "Bit NOT NULL")]
        public bool smart_pass_email_summary
        {
            get
            {
                return this._smart_pass_email_summary;
            }
            set
            {
                if ((this._smart_pass_email_summary != value))
                {
                    this.Onsmart_pass_email_summaryChanging(value);
                    this.SendPropertyChanging();
                    this._smart_pass_email_summary = value;
                    this.SendPropertyChanged("smart_pass_email_summary");
                    this.Onsmart_pass_email_summaryChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_prospecting_areas", DbType = "VarChar(MAX)")]
        public string prospecting_areas
        {
            get
            {
                return this._prospecting_areas;
            }
            set
            {
                if ((this._prospecting_areas != value))
                {
                    this.Onprospecting_areasChanging(value);
                    this.SendPropertyChanging();
                    this._prospecting_areas = value;
                    this.SendPropertyChanged("prospecting_areas");
                    this.Onprospecting_areasChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_prospecting_credits", DbType = "Decimal(18,2) NOT NULL")]
        public decimal prospecting_credits
        {
            get
            {
                return this._prospecting_credits;
            }
            set
            {
                if ((this._prospecting_credits != value))
                {
                    this.Onprospecting_creditsChanging(value);
                    this.SendPropertyChanging();
                    this._prospecting_credits = value;
                    this.SendPropertyChanged("prospecting_credits");
                    this.Onprospecting_creditsChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_prospecting_contact_sync", DbType = "Bit NOT NULL")]
        public bool prospecting_contact_sync
        {
            get
            {
                return this._prospecting_contact_sync;
            }
            set
            {
                if ((this._prospecting_contact_sync != value))
                {
                    this.Onprospecting_contact_syncChanging(value);
                    this.SendPropertyChanging();
                    this._prospecting_contact_sync = value;
                    this.SendPropertyChanged("prospecting_contact_sync");
                    this.Onprospecting_contact_syncChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_active", DbType = "Bit NOT NULL")]
        public bool active
        {
            get
            {
                return this._active;
            }
            set
            {
                if ((this._active != value))
                {
                    this.OnactiveChanging(value);
                    this.SendPropertyChanging();
                    this._active = value;
                    this.SendPropertyChanged("active");
                    this.OnactiveChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_prospecting_control", DbType = "Bit NOT NULL")]
        public bool prospecting_control
        {
            get
            {
                return this._prospecting_control;
            }
            set
            {
                if ((this._prospecting_control != value))
                {
                    this.Onprospecting_controlChanging(value);
                    this.SendPropertyChanging();
                    this._prospecting_control = value;
                    this.SendPropertyChanged("prospecting_control");
                    this.Onprospecting_controlChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_compliance_access", DbType = "Bit NOT NULL")]
        public bool compliance_access
        {
            get
            {
                return this._compliance_access;
            }
            set
            {
                if ((this._compliance_access != value))
                {
                    this.Oncompliance_accessChanging(value);
                    this.SendPropertyChanging();
                    this._compliance_access = value;
                    this.SendPropertyChanged("compliance_access");
                    this.Oncompliance_accessChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_session_key", DbType = "UniqueIdentifier")]
        public System.Nullable<System.Guid> session_key
        {
            get
            {
                return this._session_key;
            }
            set
            {
                if ((this._session_key != value))
                {
                    this.Onsession_keyChanging(value);
                    this.SendPropertyChanging();
                    this._session_key = value;
                    this.SendPropertyChanged("session_key");
                    this.Onsession_keyChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_deleted_date", DbType = "DateTime")]
        public System.Nullable<System.DateTime> deleted_date
        {
            get
            {
                return this._deleted_date;
            }
            set
            {
                if ((this._deleted_date != value))
                {
                    this.Ondeleted_dateChanging(value);
                    this.SendPropertyChanging();
                    this._deleted_date = value;
                    this.SendPropertyChanged("deleted_date");
                    this.Ondeleted_dateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_deleted_by", DbType = "Int")]
        public System.Nullable<int> deleted_by
        {
            get
            {
                return this._deleted_by;
            }
            set
            {
                if ((this._deleted_by != value))
                {
                    this.Ondeleted_byChanging(value);
                    this.SendPropertyChanging();
                    this._deleted_by = value;
                    this.SendPropertyChanged("deleted_by");
                    this.Ondeleted_byChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_control", DbType = "VarChar(MAX)")]
        public string license_control
        {
            get
            {
                return this._license_control;
            }
            set
            {
                if ((this._license_control != value))
                {
                    this.Onlicense_controlChanging(value);
                    this.SendPropertyChanging();
                    this._license_control = value;
                    this.SendPropertyChanged("license_control");
                    this.Onlicense_controlChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
#pragma warning restore 1591
