//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.contact_details = new HashSet<contact_details>();
            this.search_client = new HashSet<search_client>();
        }
    
        public int pk_client_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string preferred_name { get; set; }
        public string identity_number { get; set; }
        public string passport_number { get; set; }
        public Nullable<int> title { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> ethnic_group { get; set; }
        public string occupation { get; set; }
        public Nullable<int> fk_marital_status_type_id { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> identified { get; set; }
        public Nullable<System.DateTime> identified_date { get; set; }
        public Nullable<bool> blocked { get; set; }
        public Nullable<System.DateTime> blocked_date { get; set; }
        public Nullable<int> fk_language_id { get; set; }
        public Nullable<int> fk_religion_id { get; set; }
        public Nullable<int> fk_citizenship { get; set; }
        public Nullable<int> fk_country_of_residence { get; set; }
        public Nullable<int> preferred_language { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> deceased_status { get; set; }
    
        public virtual country_code country_code { get; set; }
        public virtual country_code country_code1 { get; set; }
        public virtual marital_status_type marital_status_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_details> contact_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<search_client> search_client { get; set; }
    }
}
