//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.DataContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<client_system> client_system { get; set; }
        public virtual DbSet<contact_details> contact_details { get; set; }
        public virtual DbSet<contact_details_location_type> contact_details_location_type { get; set; }
        public virtual DbSet<contact_details_type> contact_details_type { get; set; }
        public virtual DbSet<country_code> country_code { get; set; }
        public virtual DbSet<marital_status_type> marital_status_type { get; set; }
        public virtual DbSet<search_client> search_client { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
    }
}
