//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_client
    {
        public int pk_search_client_id { get; set; }
        public int fk_client_id { get; set; }
        public int fk_client_system_id { get; set; }
        public int fk_system_client_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string preferred_name { get; set; }
        public string identity_number { get; set; }
        public string passport_number { get; set; }
        public string date_of_birth { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_primary_contact_no { get; set; }
        public Nullable<bool> is_primary_email { get; set; }
    
        public virtual client client { get; set; }
        public virtual client_system client_system { get; set; }
    }
}
