CREATE TABLE [dbo].[license] (
    [license_id]                        INT           IDENTITY (1, 1) NOT NULL,
    [license_name]                      VARCHAR (150) NOT NULL,
    [region]                            VARCHAR (150) NOT NULL,
    [sub_region]                        VARCHAR (150) NOT NULL,
    [sub_license_name]                  VARCHAR (150) NULL,
    [registration_id]                   INT           NOT NULL,
    [manager]                           VARCHAR (150) NOT NULL,
    [residential]                       BIT           CONSTRAINT [DF_license_residential] DEFAULT ((0)) NOT NULL,
    [rental]                            BIT           CONSTRAINT [DF_license_rental] DEFAULT ((0)) NOT NULL,
    [commercial]                        BIT           CONSTRAINT [DF_license_commercial] DEFAULT ((0)) NOT NULL,
    [agricultural]                      BIT           CONSTRAINT [DF_license_agricultural] DEFAULT ((0)) NOT NULL,
    [developments]                      BIT           CONSTRAINT [DF_license_developments] DEFAULT ((0)) NOT NULL,
    [distressed]                        BIT           CONSTRAINT [DF_license_distressed] DEFAULT ((0)) NOT NULL,
    [top_twenty_region]                 CHAR (1)      NULL,
    [Status]                            CHAR (1)      CONSTRAINT [DF_license_Status] DEFAULT ('A') NULL,
    [datasheet_link]                    VARCHAR (150) NULL,
    [percentage_quota]                  INT           NULL,
    [sales_referral_residential_id]     INT           NULL,
    [rentals_referrals_residential_id]  INT           NULL,
    [sales_referral_commercial_id]      INT           NULL,
    [rentals_referrals_commercial_id]   INT           NULL,
    [sales_referral_agricultural_id]    INT           NULL,
    [rentals_referrals_agricultural_id] INT           NULL,
    [sales_referral_developments_id]    INT           NULL,
    [rentals_referrals_developments_id] INT           NULL,
    [icas]                              BIT           CONSTRAINT [DF_license_icas] DEFAULT ((0)) NOT NULL,
    [debt_remedy]                       BIT           CONSTRAINT [DF_license_debt_remedy] DEFAULT ((0)) NOT NULL,
    [cluster]                           INT           NULL,
    [google_region_key]                 VARCHAR (100) NULL,
    [google_licsense_key]               VARCHAR (100) NULL
);

