CREATE TABLE [dbo].[reports_Sales_Recognition_Detail_Global] (
    [Region]                     VARCHAR (50)    NULL,
    [License_ID]                 INT             NULL,
    [License]                    NVARCHAR (50)   NULL,
    [Agent]                      NVARCHAR (100)  NULL,
    [Recognition Unit]           DECIMAL (18, 6) NULL,
    [Recognition Amount]         DECIMAL (18, 6) NULL,
    [SPS Seeff Referral]         BIT             NULL,
    [SPS Referral Comm]          DECIMAL (18, 2) NULL,
    [Comm Paid]                  DECIMAL (18, 2) NULL,
    [SPS Comm Amount]            DECIMAL (18, 2) NULL,
    [SPS Percentage Split]       DECIMAL (18, 2) NULL,
    [SPS Transaction Type]       NVARCHAR (100)  NULL,
    [SPS Transaction Division]   NVARCHAR (100)  NULL,
    [Reg ID]                     INT             NULL,
    [Month]                      INT             NULL,
    [Partner Count]              INT             NULL,
    [SPS Referral Type]          NVARCHAR (50)   NULL,
    [SPS Transaction ID]         NVARCHAR (50)   NULL,
    [SPS Transaction Ref]        NVARCHAR (50)   NULL,
    [SPS License Deal No]        NVARCHAR (100)  NULL,
    [SPS Sold Date]              DATETIME        NULL,
    [SPS Selling Price]          DECIMAL (18, 2) NULL,
    [SPS Property ID]            BIGINT          NULL,
    [SPS Property Address]       NVARCHAR (500)  NULL,
    [SPS Created Date]           DATETIME        NULL,
    [SPS Reporting Date]         DATETIME        NULL,
    [Recognise]                  BIT             NULL,
    [Smart Pass ID]              INT             NULL,
    [Smart Pass License ID To]   INT             NULL,
    [Smart Pass License ID From] INT             NULL,
    [InsertOn]                   DATETIME        NULL,
    [Sale Comm @ 7%]             DECIMAL (18, 6) NULL
);

