CREATE TABLE [dbo].[sale_transaction] (
    [sale_transaction_id]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [sps_transaction_ref]       VARCHAR (50)    NOT NULL,
    [sps_web_ref]               VARCHAR (50)    NULL,
    [sps_lic_deal_no]           VARCHAR (100)   NULL,
    [sps_referral_type]         VARCHAR (100)   NOT NULL,
    [sps_referral_comm]         DECIMAL (18, 2) NULL,
    [sps_listed_date]           DATETIME        NULL,
    [sps_listing_price]         DECIMAL (18, 2) NULL,
    [sps_sold_date]             DATETIME        NULL,
    [sps_selling_price]         DECIMAL (18, 2) NULL,
    [sps_comm_amount]           DECIMAL (18, 2) NOT NULL,
    [sps_percentage_split]      DECIMAL (18, 2) NULL,
    [sps_transaction_division]  VARCHAR (100)   NOT NULL,
    [sps_buyer_source]          VARCHAR (250)   NOT NULL,
    [sps_seller_source]         VARCHAR (250)   NOT NULL,
    [sps_distressed_deal]       VARCHAR (3)     CONSTRAINT [DF_sale_transaction_sps_distressed_deal] DEFAULT ('No') NOT NULL,
    [sps_showdays]              INT             NULL,
    [sps_solemandate]           VARCHAR (3)     CONSTRAINT [DF_sale_transaction_sps_solemandate] DEFAULT ('No') NULL,
    [sps_funding_type]          VARCHAR (250)   NULL,
    [sps_bond_amount]           DECIMAL (18, 2) NULL,
    [sps_bank]                  VARCHAR (250)   NULL,
    [sps_bond_account_no]       VARCHAR (50)    NULL,
    [sps_originator]            VARCHAR (150)   NULL,
    [sps_originator_other]      VARCHAR (150)   NULL,
    [sps_transferring_attorney] VARCHAR (250)   NULL,
    [sps_bond_attorney]         VARCHAR (250)   NULL,
    [sps_property_id]           BIGINT          NOT NULL,
    [sps_property_address]      VARCHAR (500)   NULL,
    [sps_created_date]          DATETIME        CONSTRAINT [DF_sale_transaction_sps_created_date] DEFAULT (getdate()) NOT NULL,
    [sps_update_date]           DATETIME        NULL,
    [branch_id]                 INT             CONSTRAINT [DF_sale_transaction_branch_id] DEFAULT ((0)) NOT NULL,
    [created_by]                INT             NOT NULL,
    [update_by]                 INT             NULL,
    [newspapers_direct]         BIT             CONSTRAINT [DF_sale_transaction_newspapers_direct] DEFAULT ((0)) NOT NULL,
    [sps_property_country]      VARCHAR (150)   CONSTRAINT [DF_sale_transaction_sps_property_country] DEFAULT ('South Africa') NOT NULL,
    [smart_pass_id]             INT             NULL
);

