CREATE TABLE [dbo].[sps_transaction] (
    [sps_transaction_id]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [sps_transaction_ref]         VARCHAR (50)    NOT NULL,
    [sps_web_ref]                 VARCHAR (50)    NULL,
    [sps_lic_deal_no]             VARCHAR (100)   NULL,
    [sps_refferal_type]           VARCHAR (100)   NOT NULL,
    [sps_referral_comm]           DECIMAL (18, 2) NULL,
    [sps_listed_date]             DATETIME        NULL,
    [sps_listing_price]           DECIMAL (18, 2) NULL,
    [sps_sold_date]               DATETIME        NULL,
    [sps_selling_price]           DECIMAL (18, 2) NULL,
    [sps_comm_amount]             DECIMAL (18, 2) NOT NULL,
    [sps_percentage_split]        DECIMAL (18, 2) NULL,
    [sps_transaction_type]        VARCHAR (100)   NOT NULL,
    [sps_transaction_division]    VARCHAR (100)   NOT NULL,
    [sps_from_person_type]        VARCHAR (100)   NOT NULL,
    [sps_from_person_id]          INT             NOT NULL,
    [sps_to_person_type]          VARCHAR (100)   NOT NULL,
    [sps_to_person_id]            INT             NOT NULL,
    [sps_buyer_source]            VARCHAR (250)   NOT NULL,
    [sps_seller_source]           VARCHAR (250)   NOT NULL,
    [sps_distressed_deal]         VARCHAR (3)     CONSTRAINT [DF_sps_transaction_sps_distressed_deal] DEFAULT ('No') NOT NULL,
    [sps_showdays]                INT             NULL,
    [sps_solemandate]             VARCHAR (3)     CONSTRAINT [DF_sps_transaction_sps_solemandate] DEFAULT ('No') NULL,
    [sps_funding_type]            VARCHAR (250)   NULL,
    [sps_bond_amount]             DECIMAL (18, 2) NULL,
    [sps_bank]                    VARCHAR (250)   NULL,
    [sps_bond_account_no]         VARCHAR (50)    NULL,
    [sps_originator]              VARCHAR (150)   NULL,
    [sps_originator_other]        VARCHAR (150)   NULL,
    [sps_transferring_attorney]   VARCHAR (250)   NULL,
    [sps_bond_attorney]           VARCHAR (250)   NULL,
    [sps_expected_reg_date]       DATETIME        NULL,
    [sps_reg_date]                DATETIME        NULL,
    [sps_voyager_miles_buyer]     INT             NULL,
    [sps_voyager_no_buyer]        VARCHAR (50)    NULL,
    [sps_voucher_no_buyer]        VARCHAR (50)    NULL,
    [sps_voyager_miles_seller]    INT             NULL,
    [sps_voyager_no_seller]       VARCHAR (50)    NULL,
    [sps_voucher_no_seller]       VARCHAR (50)    NULL,
    [sps_comment]                 VARCHAR (MAX)   NULL,
    [sps_property_id]             BIGINT          NOT NULL,
    [sps_property_address]        VARCHAR (500)   NULL,
    [sps_created_date]            DATETIME        CONSTRAINT [DF_sps_transaction_sps_created_date] DEFAULT (getdate()) NOT NULL,
    [sps_update_date]             DATETIME        NULL,
    [branch_id]                   INT             CONSTRAINT [DF_sps_transaction_branch_id] DEFAULT ((0)) NOT NULL,
    [created_by]                  INT             NOT NULL,
    [update_by]                   INT             NULL,
    [newspapers_direct]           BIT             CONSTRAINT [DF_sps_transaction_newspapers_direct] DEFAULT ((0)) NOT NULL,
    [sps_rental_management_fee]   DECIMAL (18, 2) NULL,
    [sps_rental_contract_renewal] BIT             CONSTRAINT [DF_sps_transaction_sps_rental_contract_renewal] DEFAULT ((0)) NOT NULL,
    [sps_property_country]        VARCHAR (150)   CONSTRAINT [DF_sps_transaction_sps_property_country] DEFAULT ('South Africa') NOT NULL,
    [sps_reporting_date]          DATETIME        NULL,
    [sps_cancelled]               BIT             CONSTRAINT [DF_sps_transaction_sps_cancelled] DEFAULT ((0)) NOT NULL,
    [sps_seeff_referral]          BIT             CONSTRAINT [DF_sps_transaction_sps_seeff_referral] DEFAULT ((0)) NOT NULL,
    [sps_short_term_rental]       BIT             CONSTRAINT [DF_sps_transaction_sps_short_term_rental] DEFAULT ((0)) NOT NULL,
    [smart_pass_id]               INT             NULL,
    [sbf_seeff_billed]            DATETIME        NULL,
    [sbf_korbitec_paid]           DATETIME        NULL,
    [sbf_korbitec_registered]     BIT             CONSTRAINT [DF_sps_transaction_sbf_korbitec_registered] DEFAULT ((0)) NOT NULL,
    [sbf_seeff_fee]               DECIMAL (18, 2) NULL,
    [sbf_korbitec_fee]            DECIMAL (18, 2) NULL,
    [lightstone_reg_date]         DATETIME        NULL,
    [exception_id]                INT             NULL,
    [unique_id]                   VARCHAR (100)   NULL,
    CONSTRAINT [PK_sps_transaction] PRIMARY KEY CLUSTERED ([sps_transaction_id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [Indx02]
    ON [dbo].[sps_transaction]([sps_reporting_date] ASC)
    INCLUDE([sps_transaction_id], [sps_transaction_ref], [sps_lic_deal_no], [sps_refferal_type], [sps_referral_comm], [sps_listing_price], [sps_sold_date], [sps_selling_price], [sps_comm_amount], [sps_percentage_split], [sps_expected_reg_date], [sps_comment], [branch_id], [created_by]);

