CREATE TABLE [dbo].[sps_hub_transaction] (
    [sps_hub_transaction]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [sps_transaction_ref]        VARCHAR (50)    NOT NULL,
    [transaction_status]         VARCHAR (150)   NOT NULL,
    [mandate_length]             INT             NULL,
    [reserve_price]              DECIMAL (18, 2) NULL,
    [valuation_price]            DECIMAL (18, 2) NULL,
    [product_id]                 INT             NULL,
    [registration_id]            INT             NOT NULL,
    [trans_att_contact_no]       VARCHAR (50)    NULL,
    [bond_att_contact_no]        VARCHAR (50)    NULL,
    [geo_code]                   VARCHAR (100)   NULL,
    [expired_mandate]            BIT             CONSTRAINT [DF_sps_hub_transaction_expired_mandate] DEFAULT ((0)) NULL,
    [invoice_number]             VARCHAR (50)    NULL,
    [payment_date]               DATETIME        NULL,
    [reversed_deal]              BIT             CONSTRAINT [DF_sps_hub_transaction_reversed_deal] DEFAULT ((0)) NOT NULL,
    [invoice_contact]            VARCHAR (250)   NULL,
    [invoice_email_address]      VARCHAR (250)   NULL,
    [incentive]                  DECIMAL (18, 2) CONSTRAINT [DF_sps_hub_transaction_incentive] DEFAULT ((0)) NOT NULL,
    [opt_received_by_hub]        DATETIME        NULL,
    [opt_submitted]              DATETIME        NULL,
    [opt_accepted]               DATETIME        NULL,
    [opt_conditions_met]         DATETIME        NULL,
    [hub_received_to_submitted]  INT             NULL,
    [submitted_to_accepted]      INT             NULL,
    [accepted_to_conditions_met] INT             NULL,
    [received_as_solemandate]    BIT             NULL
);

