CREATE TABLE [dbo].[user_registration] (
    [registration_id]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [title]                      VARCHAR (50)  NOT NULL,
    [user_name]                  VARCHAR (250) NOT NULL,
    [user_surname]               VARCHAR (250) NOT NULL,
    [branch_id]                  INT           NOT NULL,
    [user_email_address]         VARCHAR (250) NULL,
    [user_private_email_address] VARCHAR (250) NULL,
    [user_preferred_name]        VARCHAR (250) NULL,
    [user_cellphone_no]          VARCHAR (11)  NOT NULL,
    [user_office_no]             VARCHAR (11)  NULL,
    [user_fax_no]                VARCHAR (11)  NULL,
    [designation]                VARCHAR (200) NOT NULL,
    [user_password]              VARCHAR (50)  NULL,
    [user_guid]                  VARCHAR (50)  NOT NULL,
    [created_date]               DATETIME      CONSTRAINT [DF_user_registration_update_date] DEFAULT (getdate()) NOT NULL,
    [update_date]                DATETIME      NULL,
    [reminder]                   VARCHAR (50)  NULL,
    [DOB]                        DATETIME      NULL,
    [licensee_id]                INT           NULL,
    [confirmation]               VARCHAR (1)   NULL,
    [achiever]                   VARCHAR (1)   NULL,
    [achiever_life_time]         BIT           CONSTRAINT [DF_user_registration_achiever_life_time] DEFAULT ((0)) NULL,
    [achiever_platinum]          BIT           CONSTRAINT [DF_user_registration_achiever_platinum] DEFAULT ((0)) NULL,
    [achiever_ordinary]          BIT           CONSTRAINT [DF_user_registration_achiever_ordinary] DEFAULT ((0)) NULL,
    [id_no]                      VARCHAR (13)  NULL,
    [fidelity_fund_no]           VARCHAR (20)  NULL,
    [physical_address_1]         VARCHAR (150) NULL,
    [physical_address_2]         VARCHAR (150) NULL,
    [physical_town_city]         VARCHAR (150) NULL,
    [physical_province]          VARCHAR (100) NULL,
    [physical_code]              VARCHAR (10)  NULL,
    [postal_address_1]           VARCHAR (150) NULL,
    [postal_address_2]           VARCHAR (150) NULL,
    [postal_town_city]           VARCHAR (150) NULL,
    [postal_province]            VARCHAR (100) NULL,
    [postal_code]                VARCHAR (50)  NULL,
    [smart_account]              CHAR (1)      NULL,
    [pop_account]                CHAR (1)      NULL,
    [acc_anniversary]            DATETIME      NULL,
    [home_language]              VARCHAR (100) NULL,
    [fidelity_fund_expiry]       DATETIME      NULL,
    [start_date]                 DATETIME      NULL,
    [region]                     VARCHAR (100) NULL,
    [sub_region]                 VARCHAR (100) NULL,
    [gender]                     VARCHAR (1)   NULL,
    [sa_citizen]                 VARCHAR (1)   NULL,
    [fkAgentId]                  INT           NULL,
    [license_referral_contact]   BIT           CONSTRAINT [DF_user_registration_license_referral_contact] DEFAULT ((0)) NOT NULL,
    [birthday_wish]              BIT           CONSTRAINT [DF_user_registration_birthday_wish] DEFAULT ((1)) NOT NULL,
    [birthday_display]           BIT           CONSTRAINT [DF_user_registration_birthday_display] DEFAULT ((1)) NOT NULL,
    [icas]                       BIT           CONSTRAINT [DF_user_registration_ICAS] DEFAULT ((0)) NOT NULL,
    [search_group]               INT           NULL,
    [ms_area_permissions]        VARCHAR (MAX) NULL,
    [smart_pass_email_summary]   BIT           CONSTRAINT [DF_user_registration_smart_pass_email_summary] DEFAULT ((0)) NOT NULL,
    [prospecting_areas]          VARCHAR (MAX) NULL,
    [prospecting_credits]        INT           CONSTRAINT [DF__user_regi__prosp__67F21338] DEFAULT ((0)) NOT NULL,
    [prospecting_contact_sync]   BIT           CONSTRAINT [DF_user_registration_prospecting_contact_sync] DEFAULT ((0)) NOT NULL,
    [active]                     BIT           CONSTRAINT [DF_user_registration_active] DEFAULT ((0)) NOT NULL,
    [prospecting_control]        BIT           CONSTRAINT [DF_user_registration_prospecting_control] DEFAULT ((0)) NOT NULL,
    [compliance_access]          BIT           CONSTRAINT [DF_user_registration_compliance_access] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_user_registration] PRIMARY KEY CLUSTERED ([registration_id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [non_clustered_index_registration_id]
    ON [dbo].[user_registration]([registration_id] ASC);

