//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ProspectingProject.lightstoneSeeffService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SeeffSoap", Namespace="http://tempuri.org/")]
    public partial class Seeff : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback returnAreaPropType_batchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback returnAreaPropTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnProperties_SeefOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Seeff() {
            this.Url = global::ProspectingProject.Properties.Settings.Default.ProspectingProject_lightstoneSeeffService_Seeff;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event returnAreaPropType_batchesCompletedEventHandler returnAreaPropType_batchesCompleted;
        
        /// <remarks/>
        public event returnAreaPropTypeCompletedEventHandler returnAreaPropTypeCompleted;
        
        /// <remarks/>
        public event ReturnPropertiesCompletedEventHandler ReturnPropertiesCompleted;
        
        /// <remarks/>
        public event ReturnProperties_SeefCompletedEventHandler ReturnProperties_SeefCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/returnAreaPropType_batches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet returnAreaPropType_batches(string user_id) {
            object[] results = this.Invoke("returnAreaPropType_batches", new object[] {
                        user_id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void returnAreaPropType_batchesAsync(string user_id) {
            this.returnAreaPropType_batchesAsync(user_id, null);
        }
        
        /// <remarks/>
        public void returnAreaPropType_batchesAsync(string user_id, object userState) {
            if ((this.returnAreaPropType_batchesOperationCompleted == null)) {
                this.returnAreaPropType_batchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnAreaPropType_batchesOperationCompleted);
            }
            this.InvokeAsync("returnAreaPropType_batches", new object[] {
                        user_id}, this.returnAreaPropType_batchesOperationCompleted, userState);
        }
        
        private void OnreturnAreaPropType_batchesOperationCompleted(object arg) {
            if ((this.returnAreaPropType_batchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnAreaPropType_batchesCompleted(this, new returnAreaPropType_batchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/returnAreaPropType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet returnAreaPropType(int Year, int Month, string user_id) {
            object[] results = this.Invoke("returnAreaPropType", new object[] {
                        Year,
                        Month,
                        user_id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void returnAreaPropTypeAsync(int Year, int Month, string user_id) {
            this.returnAreaPropTypeAsync(Year, Month, user_id, null);
        }
        
        /// <remarks/>
        public void returnAreaPropTypeAsync(int Year, int Month, string user_id, object userState) {
            if ((this.returnAreaPropTypeOperationCompleted == null)) {
                this.returnAreaPropTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnAreaPropTypeOperationCompleted);
            }
            this.InvokeAsync("returnAreaPropType", new object[] {
                        Year,
                        Month,
                        user_id}, this.returnAreaPropTypeOperationCompleted, userState);
        }
        
        private void OnreturnAreaPropTypeOperationCompleted(object arg) {
            if ((this.returnAreaPropTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnAreaPropTypeCompleted(this, new returnAreaPropTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnProperties", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReturnProperties(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y) {
            object[] results = this.Invoke("ReturnProperties", new object[] {
                        User_ID,
                        Province,
                        Municipality,
                        DeedTown,
                        Erf,
                        Portion,
                        Sectional_Title,
                        Unit,
                        Suburb,
                        Street,
                        StreetNumber,
                        Owner_Name,
                        ID_CK,
                        Estate_Name,
                        FARM_NAME,
                        MaxRowsToReturn,
                        TrackingNumber,
                        Area_Type,
                        x,
                        y});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnPropertiesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y) {
            this.ReturnPropertiesAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Owner_Name, ID_CK, Estate_Name, FARM_NAME, MaxRowsToReturn, TrackingNumber, Area_Type, x, y, null);
        }
        
        /// <remarks/>
        public void ReturnPropertiesAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y, 
                    object userState) {
            if ((this.ReturnPropertiesOperationCompleted == null)) {
                this.ReturnPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnPropertiesOperationCompleted);
            }
            this.InvokeAsync("ReturnProperties", new object[] {
                        User_ID,
                        Province,
                        Municipality,
                        DeedTown,
                        Erf,
                        Portion,
                        Sectional_Title,
                        Unit,
                        Suburb,
                        Street,
                        StreetNumber,
                        Owner_Name,
                        ID_CK,
                        Estate_Name,
                        FARM_NAME,
                        MaxRowsToReturn,
                        TrackingNumber,
                        Area_Type,
                        x,
                        y}, this.ReturnPropertiesOperationCompleted, userState);
        }
        
        private void OnReturnPropertiesOperationCompleted(object arg) {
            if ((this.ReturnPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnPropertiesCompleted(this, new ReturnPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnProperties_Seef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReturnProperties_Seef(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int Prop_ID, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y) {
            object[] results = this.Invoke("ReturnProperties_Seef", new object[] {
                        User_ID,
                        Province,
                        Municipality,
                        DeedTown,
                        Erf,
                        Portion,
                        Sectional_Title,
                        Unit,
                        Suburb,
                        Street,
                        StreetNumber,
                        Street_Type,
                        Registrar,
                        FirstName,
                        SecondName,
                        Surname,
                        Owner_Name,
                        ID_CK,
                        Estate_Name,
                        FARM_NAME,
                        Prop_ID,
                        MaxRowsToReturn,
                        TrackingNumber,
                        Area_Type,
                        x,
                        y});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnProperties_SeefAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int Prop_ID, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y) {
            this.ReturnProperties_SeefAsync(User_ID, Province, Municipality, DeedTown, Erf, Portion, Sectional_Title, Unit, Suburb, Street, StreetNumber, Street_Type, Registrar, FirstName, SecondName, Surname, Owner_Name, ID_CK, Estate_Name, FARM_NAME, Prop_ID, MaxRowsToReturn, TrackingNumber, Area_Type, x, y, null);
        }
        
        /// <remarks/>
        public void ReturnProperties_SeefAsync(
                    string User_ID, 
                    string Province, 
                    string Municipality, 
                    string DeedTown, 
                    string Erf, 
                    string Portion, 
                    string Sectional_Title, 
                    string Unit, 
                    string Suburb, 
                    string Street, 
                    string StreetNumber, 
                    string Street_Type, 
                    string Registrar, 
                    string FirstName, 
                    string SecondName, 
                    string Surname, 
                    string Owner_Name, 
                    string ID_CK, 
                    string Estate_Name, 
                    string FARM_NAME, 
                    int Prop_ID, 
                    int MaxRowsToReturn, 
                    string TrackingNumber, 
                    string Area_Type, 
                    double x, 
                    double y, 
                    object userState) {
            if ((this.ReturnProperties_SeefOperationCompleted == null)) {
                this.ReturnProperties_SeefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnProperties_SeefOperationCompleted);
            }
            this.InvokeAsync("ReturnProperties_Seef", new object[] {
                        User_ID,
                        Province,
                        Municipality,
                        DeedTown,
                        Erf,
                        Portion,
                        Sectional_Title,
                        Unit,
                        Suburb,
                        Street,
                        StreetNumber,
                        Street_Type,
                        Registrar,
                        FirstName,
                        SecondName,
                        Surname,
                        Owner_Name,
                        ID_CK,
                        Estate_Name,
                        FARM_NAME,
                        Prop_ID,
                        MaxRowsToReturn,
                        TrackingNumber,
                        Area_Type,
                        x,
                        y}, this.ReturnProperties_SeefOperationCompleted, userState);
        }
        
        private void OnReturnProperties_SeefOperationCompleted(object arg) {
            if ((this.ReturnProperties_SeefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnProperties_SeefCompleted(this, new ReturnProperties_SeefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void returnAreaPropType_batchesCompletedEventHandler(object sender, returnAreaPropType_batchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnAreaPropType_batchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnAreaPropType_batchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void returnAreaPropTypeCompletedEventHandler(object sender, returnAreaPropTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnAreaPropTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnAreaPropTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReturnPropertiesCompletedEventHandler(object sender, ReturnPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReturnProperties_SeefCompletedEventHandler(object sender, ReturnProperties_SeefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnProperties_SeefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnProperties_SeefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591