CREATE TABLE [dbo].[base_data](
	[ls_area_id] [int] NULL,
	[seeff_lic_area] [varchar](100) NULL,
	[property_id] [int] NULL,
	[iregdate] [varchar](8) NULL,
	[ipurchdate] [numeric](11, 0) NULL,
	[title_deed_no] [varchar](20) NULL,
	[non_gar_props_on_title] [numeric](18, 0) NULL,
	[purch_price] [numeric](18, 0) NULL,
	[erf_key] [varchar](60) NULL,
	[ea_code] [varchar](10) NULL,
	[suburb] [varchar](40) NULL,
	[munic_name] [varchar](40) NULL,
	[province] [varchar](40) NULL,
	[property_type] [varchar](3) NULL,
	[ss_fh] [varchar](4) NULL,
	[property_currently_in_pvt_hands] [varchar](10) NULL,
	[private_registration] [varchar](10) NULL,
	[bonded_transfer] [varchar](20) NULL,
	[suburb_id] [int] NULL,
	[erf_size] [numeric](18, 0) NULL,
	[buyer_name] [varchar](70) NULL,
	[seller_name] [varchar](70) NULL,
	[property_address] [varchar](255) NULL,
	[street_or_unit_no] [varchar](255) NULL,
	[ls_resflg] [bit] NULL,
	[estate_name] [varchar](100) NULL,
	[buyer_name_2] [varchar](100) NULL,
	[multibuyer] [varchar](10) NULL,
	[seeff_suburb] [varchar](100) NULL,
	[seeff_suburb_id] [int] NULL,
	[seeff_suburb_type] [varchar](10) NULL,
	[seeff_lic_id] [int] NULL,
	[x] [decimal](13, 8) NULL,
	[y] [decimal](13, 8) NULL,
	[seeff_area_id] [int] NULL,
	[unique_id] [nvarchar](50) NULL,
	[seeff_deal] [bit] NULL,
	[fated] [bit] NULL,
	[market_share_type] [varchar](1) NULL,
	[base_data_id] [int] IDENTITY(1,1) NOT NULL,
	[agency_id] [int] NULL,
[erf_no] int null,
[portion_no]  int null
 CONSTRAINT [pk_base_data_id] PRIMARY KEY CLUSTERED 
(
	[base_data_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
